---
title: "5'CutSiteAnalysisDataGeneration"
author: "Ben MOrledge-Hampton"
date: '2022-07-14'
output: html_document
params:
  bioinformaticsDirectory:
    label: "Bioinformatics Projects Directory"
    value: C:/Bioinformatics_Projects
    input: select
    choices: [C:/Bioinformatics_Projects, F:/Bioinformatics_Projects]
  filtering:
    label: "Filtering"
    value: NONE
    input: select
    choices: [NONE, TGG_filtered, TG_filtered]
---


```{r setup_chunk}
library(knitr)

expansionOffset = 10

if (interactive()) {
  bioinformaticsDirectory = choose.dir(caption = "Select Bioinformatics_Projects Directory")
  filtering = readline("Filtering identifier (Input nothing for no filtering):")
  if (filtering == '') filtering = character()
} else {
  bioinformaticsDirectory = params$bioinformaticsDirectory
  filtering = params$filtering
  if (filtering == "NONE") filtering = character()
}

if (is.na(bioinformaticsDirectory)) stop("No bioinformatics directory given.")

deaminationDataDirectory = file.path(bioinformaticsDirectory, "deamination_determination", "data")
NHF1GeneralReadSequenceDataDirectory = file.path(deaminationDataDirectory, "NHF1", "general_read_sequences")
GM12878GeneralReadSequenceDataDirectory = file.path(deaminationDataDirectory, "GM12878", "general_read_sequences")
DmGeneralReadSequenceDataDirectory = file.path(deaminationDataDirectory, "Dm", "general_read_sequences")
arabidopsisGeneralReadSequenceDataDirectory = file.path(deaminationDataDirectory, "Arabidopsis", "general_read_sequences")
yeastGeneralReadSequenceDataDirectory = file.path(deaminationDataDirectory, "yeast", "general_read_sequences")
EColiGeneralReadSequenceDataDirectory = file.path(deaminationDataDirectory, "E_coli_WT", "general_read_sequences")

humanReadMinMax = c(22, 30)
drosophilaReadMinMax = c(23, 32)
arabidopsisReadMinMax = c(24, 30)
yeastReadMinMax = c(22, 25)
EColiReadMinMax = c(11, 13)
```


```{r source_functions}
source(file.path(bioinformaticsDirectory, "deamination_determination", 'R',
                 "UsefulFileSystemFunctions.R"))
source(file.path(bioinformaticsDirectory, "deamination_determination", 'R',
                 "DeaminationAnchoredExcisionSiteAnalysis.R"))
```


```{r define_all_that_and_a_bag_of_chips_function}
cutSiteAnalysis = function(lesion, repetition, timepoint, cellType, directory,
                           queryPattern, sequencesName, readMinMax,
                           alsoComputeCombinedReadLengths = FALSE, alsoComputeNucFreq = FALSE) {
  readData = fread(generateFilePath(
    directory, dataTypeStrings$alignedReads , ".bed",
    cellType = cellType, lesion = lesion, timepoint = timepoint,
    repitition = repetition, expansionNum = expansionOffset, filtering = filtering
  ))
  readData = data.table(Read_Length = nchar(readData$V7)-expansionOffset*2, Read_Sequence = readData$V7)
  readData = readData[Read_Length >= readMinMax[1] & Read_Length <= readMinMax[2]]

  seqFreq = getSequenceFreqByReadLengthAndPos(readData, queryPattern = queryPattern, posType = FIVE_PRIME)
  seqFreq[, Position := Position - 10]
  
  fwrite(seqFreq, sep = '\t', file = generateFilePath(
    directory = directory, dataTypeStrings$sequenceFrequency, ".tsv",
    cellType = cellType, lesion = lesion, repitition = repetition,
    timepoint = timepoint, sequence = sequencesName, filtering = filtering))
  
  if (alsoComputeNucFreq) {
    
    nucFreq = tabulateNucFreqByPosTimepointAndLength(setNames(list(readData),timepoint), FIVE_PRIME)
    nucFreq[, Position := Position - 10]
    
    fwrite(nucFreq, sep = '\t', file = generateFilePath(
      directory = directory, dataTypeStrings$nucleotideFrequencyData, ".tsv",
      cellType = cellType, lesion = lesion, repitition = repetition,
      timepoint = timepoint, filtering = filtering))
    
  }
  
  if (alsoComputeCombinedReadLengths) {
    readData[, Read_Length := NULL]
    readData[, Read_Length := "combined"]
    
    seqFreq = getSequenceFreqByReadLengthAndPos(readData, queryPattern = queryPattern, posType = FIVE_PRIME)
    seqFreq[, Position := Position - 10]
    
    fwrite(seqFreq, sep = '\t', file = generateFilePath(
        directory = directory, dataTypeStrings$sequenceFrequency, ".tsv",
        cellType = cellType, lesion = lesion, repitition = repetition,
        timepoint = timepoint, sequence = sequencesName, filtering = filtering,
        additionalInformation = "combined_read_lengths"))
    
    if (alsoComputeNucFreq) {
    
      nucFreq = tabulateNucFreqByPosTimepointAndLength(setNames(list(readData),timepoint), FIVE_PRIME)
      nucFreq[, Position := Position - 10]
      
      fwrite(nucFreq, sep = '\t', file = generateFilePath(
        directory = directory, dataTypeStrings$nucleotideFrequencyData, ".tsv",
        cellType = cellType, lesion = lesion, repitition = repetition,
        timepoint = timepoint, filtering = filtering, additionalInformation = "combined_read_lengths"))
    
  }
    
  }
}
```


```{r compute_and_write_sequence_frequencies}
HYV = c("ACA","ACC","ACG","ATA","ATC","ATG",
        "CCA","CCC","CCG","CTA","CTC","CTG",
        "TCA","TCC","TCG","TTA","TTC","TTG")
HYVPattern = "^[ACT][CT][ACG]"

cutSiteAnalysis("CPD", "all_reps", "1h", "NHF1", NHF1GeneralReadSequenceDataDirectory,
                HYVPattern, "HYV", humanReadMinMax, alsoComputeCombinedReadLengths = TRUE,
                alsoComputeNucFreq = TRUE)
cutSiteAnalysis("6-4", "all_reps", "20min", "NHF1", NHF1GeneralReadSequenceDataDirectory,
                HYVPattern, "HYV", humanReadMinMax, alsoComputeCombineReadLengths = TRUE)
cutSiteAnalysis("cisplatin", "rep1", "90min", "GM12878", GM12878GeneralReadSequenceDataDirectory,
                HYVPattern, "HYV", humanReadMinMax, alsoComputeCombinedReadLengths = TRUE)
cutSiteAnalysis("CPD", "all_reps", "20min", "yeast", yeastGeneralReadSequenceDataDirectory,
                HYVPattern, "HYV", yeastReadMinMax, alsoComputeCombinedReadLengths = TRUE)
cutSiteAnalysis("CPD", "all_reps", "ZT2", "Arabidopsis", arabidopsisGeneralReadSequenceDataDirectory,
                HYVPattern, "HYV", arabidopsisReadMinMax, alsoComputeCombinedReadLengths = TRUE)
cutSiteAnalysis("CPD", "all_reps", "5min", "E_coli_WT", EColiGeneralReadSequenceDataDirectory,
                HYVPattern, "HYV", EColiReadMinMax, alsoComputeCombinedReadLengths = TRUE)
```

