---
title: "CS-B General Read Sequence Figure Generation"
author: "Ben Morledge-Hampton"
date: "5/2/2022"
output: html_document
params:
  bioinformaticsDirectory:
    label: "Bioinformatics Projects Directory"
    value: C:/Bioinformatics_Projects
    input: select
    choices: [C:/Bioinformatics_Projects, F:/Bioinformatics_Projects]
---


```{r setup_chunk}
library(knitr)

expansionOffset = 10
cellType = "CS-B"
CPDTimepoints = list(`1h` = NULL)
sixFourTimepoints = list(`1h` = NULL)
repNames = c("rep1", "rep2", "all_reps")
minReadLength = 22; maxReadLength = 30

opts_chunk$set(dev = "png", dpi = 600, fig.width = 7, fig.height = 5,
               fig.path = paste0(file.path("deamination_analysis_output", cellType,
                                           "general_read_analysis_figures"),
                                 .Platform$file.sep))
if (interactive()) {
  bioinformaticsDirectory = choose.dir(caption = "Select Bioinformatics_Projects Directory")
} else {
  bioinformaticsDirectory = params$bioinformaticsDirectory
}

if (is.na(bioinformaticsDirectory)) stop("No bioinformatics directory given.")

deaminationDataDirectory = file.path(bioinformaticsDirectory, "deamination_determination", "data", cellType)
generalReadSequenceDataDirectory = file.path(deaminationDataDirectory, "general_read_sequences")
```


```{r source_functions}
source(file.path(bioinformaticsDirectory, "deamination_determination", 'R',
                 "UsefulFileSystemFunctions.R"))
source(file.path(bioinformaticsDirectory, "deamination_determination", 'R',
                 "DeaminationSequenceAndPositionAnalysis.R"))
source(file.path(bioinformaticsDirectory, "deamination_determination", 'R',
                 "DeaminationAnchoredExcisionSiteAnalysis.R"))
```


```{r read_sequence_frequencies}
CPDTGGSeqFreq = list(rep1 = CPDTimepoints, rep2 = CPDTimepoints, all_reps = CPDTimepoints)
for (i in seq_along(CPDTGGSeqFreq)) {
  for (j in seq_along(CPDTGGSeqFreq[[i]])) {
    CPDTGGSeqFreq[[i]][[j]] = fread(generateFilePath(
      directory = generalReadSequenceDataDirectory, dataTypeStrings$sequenceFrequency, ".tsv",
      cellType = cellType, lesion = "CPD", repitition = names(CPDTGGSeqFreq)[i],
      timepoint = names(CPDTGGSeqFreq[[i]])[j], sequence = "TGG"
    ))
  }
}

CPDCGASeqFreq = list(rep1 = CPDTimepoints, rep2 = CPDTimepoints, all_reps = CPDTimepoints)
for (i in seq_along(CPDCGASeqFreq)) {
  for (j in seq_along(CPDCGASeqFreq[[i]])) {
    CPDCGASeqFreq[[i]][[j]] = fread(generateFilePath(
      directory = generalReadSequenceDataDirectory, dataTypeStrings$sequenceFrequency, ".tsv",
      cellType = cellType, lesion = "CPD", repitition = names(CPDCGASeqFreq)[i],
      timepoint = names(CPDCGASeqFreq[[i]])[j], sequence = "CGA"
    ))
  }
}


sixFourTGGSeqFreq = list(rep1 = sixFourTimepoints, rep2 = sixFourTimepoints, all_reps = sixFourTimepoints)
for (i in seq_along(sixFourTGGSeqFreq)) {
  for (j in seq_along(sixFourTGGSeqFreq[[i]])) {
    sixFourTGGSeqFreq[[i]][[j]] = fread(generateFilePath(
      directory = generalReadSequenceDataDirectory, dataTypeStrings$sequenceFrequency, ".tsv",
      cellType = cellType, lesion = "6-4", repitition = names(sixFourTGGSeqFreq)[i],
      timepoint = names(sixFourTGGSeqFreq[[i]])[j], sequence = "TGG"
    ))
  }
}

sixFourCGASeqFreq = list(rep1 = sixFourTimepoints, rep2 = sixFourTimepoints, all_reps = sixFourTimepoints)
for (i in seq_along(sixFourCGASeqFreq)) {
  for (j in seq_along(sixFourCGASeqFreq[[i]])) {
    sixFourCGASeqFreq[[i]][[j]] = fread(generateFilePath(
      directory = generalReadSequenceDataDirectory, dataTypeStrings$sequenceFrequency, ".tsv",
      cellType = cellType, lesion = "6-4", repitition = names(sixFourCGASeqFreq)[i],
      timepoint = names(sixFourCGASeqFreq[[i]])[j], sequence = "CGA"
    ))
  }
}
```


```{r CPD_sequence_frequencies, fig.width = 11, fig.height = 10}
for (i in seq_along(CPDTGGSeqFreq)) {
  plotSequenceFrequencies(CPDTGGSeqFreq[[i]], title = paste("CPD TGG Frequencies", repNames[i]),
                          expansionOffset = expansionOffset, showThreePrimeCutSite = TRUE,
                          showFivePrimeCutSite = TRUE, querySequences = c("TGG"))
}

for (i in seq_along(CPDCGASeqFreq)) {
  plotSequenceFrequencies(CPDCGASeqFreq[[i]], title = paste("CPD CGA Frequencies", repNames[i]),
                          expansionOffset = expansionOffset, showThreePrimeCutSite = TRUE,
                          showFivePrimeCutSite = TRUE, querySequences = c("CGA"))
}
```


```{r 6-4_sequence_frequencies, fig.width = 11, fig.height = 10}
for (i in seq_along(sixFourTGGSeqFreq)) {
  plotSequenceFrequencies(sixFourTGGSeqFreq[[i]], title = paste("6-4 TGG Frequencies", repNames[i]),
                          expansionOffset = expansionOffset, showThreePrimeCutSite = TRUE,
                          showFivePrimeCutSite = TRUE, querySequences = c("TGG"))
}

for (i in seq_along(sixFourCGASeqFreq)) {
  plotSequenceFrequencies(sixFourCGASeqFreq[[i]], title = paste("6-4 CGA Frequencies", repNames[i]),
                          expansionOffset = expansionOffset, showThreePrimeCutSite = TRUE,
                          showFivePrimeCutSite = TRUE, querySequences = c("CGA"))
}
```


```{r read_length_frequencies_plotting_function}
readAndPlotReadLengthFrequencies = function(lesion, repitition, timepoints) {
  
  readLengthCountsByTimepoint = timepoints
  for (i in seq_along(readLengthCountsByTimepoint)) {
    readLengthCountsByTimepoint[[i]] = fread(generateFilePath(
      generalReadSequenceDataDirectory, dataTypeStrings$readLengthcounts, ".tsv",
      cellType = cellType, lesion = lesion, timepoint = names(readLengthCountsByTimepoint)[i],
      repitition = repitition
    ))
  }
  
  plotReadLengthFrequencies(readLengthCountsByTimepoint,
                            title = paste(lesion, "Read Length Freq", repitition))
  
}
```


```{r CPD_read_length_frequencies}
for (rep in repNames) {
  readAndPlotReadLengthFrequencies("CPD", rep, CPDTimepoints)
}
```


```{r 6-4_read_length_frequencies}
for (rep in repNames) {
readAndPlotReadLengthFrequencies("6-4", rep, sixFourTimepoints)
}
```

