---
title: "CS-B Tandem Deamination Figure Generation"
author: "Ben Morledge-Hampton"
date: "5/2/2022"
output: html_document
params:
  bioinformaticsDirectory:
    label: "Bioinformatics Projects Directory"
    value: C:/Bioinformatics_Projects
    input: select
    choices: [C:/Bioinformatics_Projects, F:/Bioinformatics_Projects]
  filtering:
    label: "Filtering"
    value: NONE
    input: select
    choices: [NONE, TGG_filtered]
  mismatchType:
    label: "Mismatch Type"
    value: CC>TT
    input: select
    choices: [CC>TT, GG>AA]
---


```{r setup_chunk}
library(knitr)
library(stringr)

expansionOffset = 10
cellType = "CS-B"
CPDTimepoints = list(`1h` = NULL)
sixFourTimepoints = list(`1h` = NULL)
repNames = c("rep1", "rep2", "all_reps")
minReadLength = 22; maxReadLength = 30

if (interactive()) {
  bioinformaticsDirectory = choose.dir(caption = "Select Bioinformatics_Projects Directory")
  filtering = readline("Filtering identifier (Input nothing for no filtering):")
  if (filtering == '') filtering = character()
  mismatchType = readline("Tandem mismatch type:")
} else {
  bioinformaticsDirectory = params$bioinformaticsDirectory
  filtering = params$filtering
  if (filtering == "NONE") filtering = character()
  mismatchType = params$mismatchType
}
if (length(filtering) > 0) {
  titleCaseFiltering = tools::toTitleCase(gsub('_', ' ', filtering))
} else titleCaseFiltering = character()
titleCaseMismatchType = tools::toTitleCase(gsub('>', " To ", mismatchType))

opts_chunk$set(dev = "png", dpi = 600, fig.width = 7, fig.height = 5, 
               fig.path = paste0(file.path("deamination_analysis_output",cellType,
                                           paste(c(filtering,
                                                   gsub('>', "_to_", mismatchType),
                                                   "tandem_deamination_figures"), collapse = '_')),
                                 .Platform$file.sep))

deaminationDataDirectory = file.path(bioinformaticsDirectory, "deamination_determination", "data", cellType)
deaminationSequenceAndPositionDataDirectory = file.path(deaminationDataDirectory,"sequence_and_position_analysis")
deaminationExcisionSiteDataDirectory = file.path(deaminationDataDirectory, "excision_site_analysis")
```


```{r source_functions}
source(file.path(bioinformaticsDirectory, "deamination_determination", 'R',
                 "UsefulFileSystemFunctions.R"))
source(file.path(bioinformaticsDirectory, "deamination_determination", 'R',
                 "DeaminationSequenceAndPositionAnalysis.R"))
source(file.path(bioinformaticsDirectory, "deamination_determination", 'R',
                 "DeaminationAnchoredExcisionSiteAnalysis.R"))
```


```{r read_simplified_mismatch_data}
# Get file paths for the mismatch by read data
CPDMismatchData = list(rep1 = CPDTimepoints, rep2 = CPDTimepoints, all_reps = CPDTimepoints)
for (i in seq_along(CPDMismatchData)) {
  for (j in seq_along(CPDMismatchData[[i]])) {
    CPDMismatchData[[i]][[j]] = fread(generateFilePath(
      deaminationSequenceAndPositionDataDirectory, dataTypeStrings$simplifiedMismatches, ".tsv",
      cellType = cellType, lesion = "CPD", timepoint = names(CPDMismatchData[[i]])[j],
      repitition = names(CPDMismatchData)[i], filtering = filtering, includedMismatches = mismatchType
    ))
  }
}

sixFourMismatchData = list(rep1 = sixFourTimepoints, rep2 = sixFourTimepoints, all_reps = sixFourTimepoints)
for (i in seq_along(sixFourMismatchData)) {
  for (j in seq_along(sixFourMismatchData[[i]])) {
    sixFourMismatchData[[i]][[j]] = fread(generateFilePath(
      deaminationSequenceAndPositionDataDirectory, dataTypeStrings$simplifiedMismatches, ".tsv",
      cellType = cellType, lesion = "6-4", timepoint = names(sixFourMismatchData[[i]])[j],
      repitition = names(sixFourMismatchData)[i], filtering = filtering, includedMismatches = mismatchType
    ))
  }
}
```


```{r CPD_mismatch_pos_frequency}
for (i in 1:length(CPDMismatchData)) {
  for (j in 1:length(CPDMismatchData[[i]])) {
    plotMismatchPositionFrequencies(CPDMismatchData[[i]][[j]],
                                    title = paste(c("CPD", titleCaseFiltering, titleCaseMismatchType,
                                                    names(CPDMismatchData)[i], 
                                                    names(CPDMismatchData[[i]])[j], "Mismatch Pos"),
                                                  collapse = ' '))
  }
}
```


```{r 6-4_mismatch_pos_frequency}
for (i in 1:length(sixFourMismatchData)) {
  for (j in 1:length(sixFourMismatchData[[i]])) {
    plotMismatchPositionFrequencies(sixFourMismatchData[[i]][[j]],
                                    title = paste(c("6-4", titleCaseFiltering, titleCaseMismatchType,
                                                    names(sixFourMismatchData)[i], 
                                                    names(sixFourMismatchData[[i]])[j], "Mismatch Pos"),
                                                  collapse = ' '))
  }
}
```


```{r read_mismatch_frequency_z-score_tables}
CPDMMFreqZScores = list(rep1 = CPDTimepoints, rep2 = CPDTimepoints, all_reps = CPDTimepoints)
for (i in seq_along(CPDMMFreqZScores)) {
  for (j in seq_along(CPDMMFreqZScores[[i]])) {
    CPDMMFreqZScores[[i]][[j]] = fread(generateFilePath(
      directory = deaminationSequenceAndPositionDataDirectory, dataTypeStrings$mismatchFrequencyZScores, ".tsv",
      cellType = cellType, lesion = "CPD", repitition = names(CPDMMFreqZScores)[i],
      timepoint = names(CPDMMFreqZScores[[i]])[j], filtering = filtering, includedMismatches = mismatchType
    ))
  }
}

sixFourMMFreqZScores = list(rep1 = sixFourTimepoints, rep2 = sixFourTimepoints, all_reps = sixFourTimepoints)
for (i in seq_along(sixFourMMFreqZScores)) {
  for (j in seq_along(sixFourMMFreqZScores[[i]])) {
    sixFourMMFreqZScores[[i]][[j]] = fread(generateFilePath(
      directory = deaminationSequenceAndPositionDataDirectory, dataTypeStrings$mismatchFrequencyZScores, ".tsv",
      cellType = cellType, lesion = "6-4", repitition = names(sixFourMMFreqZScores)[i],
      timepoint = names(sixFourMMFreqZScores[[i]])[j], filtering = filtering, includedMismatches = mismatchType
    ))
  }
}
```


```{r CPD_mismatch_position_frequencies_by_read_length, fig.width = 9, fig.height = 5}
for (i in seq_along(CPDMismatchData)) {
  plotPositionAcrossTimepointAndReadLength(CPDMismatchData[[i]],
                                           title = paste(c("CPD", titleCaseFiltering, titleCaseMismatchType,
                                                           "Mismatch Pos Freq", repNames[i]),
                                                         collapse = ' '),
                                           zScoreTables = CPDMMFreqZScores[[i]])
  plotPositionAcrossTimepointAndReadLength(CPDMismatchData[[i]], posType = FIVE_PRIME,
                                           title = paste(c("CPD", titleCaseFiltering, titleCaseMismatchType,
                                                           "Mismatch Pos Freq", repNames[i]),
                                                         collapse = ' '),
                                           zScoreTables = CPDMMFreqZScores[[i]])
}
```


```{r 6-4_mismatch_position_frequencies_by_read_length, fig.width = 9, fig.height = 5}
for (i in seq_along(sixFourMismatchData)) {
  plotPositionAcrossTimepointAndReadLength(sixFourMismatchData[[i]],
                                           title = paste(c("6-4", titleCaseFiltering, titleCaseMismatchType,
                                                           "Mismatch Pos Freq", repNames[i]),
                                                         collapse = ' '),
                                           zScoreTables = sixFourMMFreqZScores[[i]])
  plotPositionAcrossTimepointAndReadLength(sixFourMismatchData[[i]], posType = FIVE_PRIME,
                                           title = paste(c("6-4", titleCaseFiltering, titleCaseMismatchType,
                                                           "Mismatch Pos Freq", repNames[i]),
                                                         collapse = ' '),
                                           zScoreTables = sixFourMMFreqZScores[[i]])
}
```


```{r read_read_length_counts}
CPDReadLengthCounts = list(rep1 = CPDTimepoints, rep2 = CPDTimepoints, all_reps = CPDTimepoints)
for (i in seq_along(CPDReadLengthCounts)) {
  for (j in seq_along(CPDReadLengthCounts[[i]])) {
    CPDReadLengthCounts[[i]][[j]] = fread(generateFilePath(
      directory = deaminationSequenceAndPositionDataDirectory, dataTypeStrings$readLengthcounts, ".tsv",
      cellType = cellType, lesion = "CPD", repitition = names(CPDReadLengthCounts)[i],
      timepoint = names(CPDReadLengthCounts[[i]])[j], filtering = filtering, includedMismatches = mismatchType
    ))
  }
}

sixFourReadLengthCounts = list(rep1 = sixFourTimepoints, rep2 = sixFourTimepoints, all_reps = sixFourTimepoints)
for (i in seq_along(sixFourReadLengthCounts)) {
  for (j in seq_along(sixFourReadLengthCounts[[i]])) {
    sixFourReadLengthCounts[[i]][[j]] = fread(generateFilePath(
      directory = deaminationSequenceAndPositionDataDirectory, dataTypeStrings$readLengthcounts, ".tsv",
      cellType = cellType, lesion = "6-4", repitition = names(sixFourReadLengthCounts)[i],
      timepoint = names(sixFourReadLengthCounts[[i]])[j], filtering = filtering, includedMismatches = mismatchType
    ))
  }
}
```


```{r CPD_read_length_distributions}
for (i in seq_along(CPDReadLengthCounts)) {
  plotReadLengthFrequencies(CPDReadLengthCounts[[i]],
                            title = paste(c("CPD", titleCaseFiltering, titleCaseMismatchType,
                                            "Read Length Freq", repNames[i]), collapse = ' '))
}
```


```{r 6-4_read_length_distributions}
for (i in seq_along(sixFourReadLengthCounts)) {
  plotReadLengthFrequencies(sixFourReadLengthCounts[[i]],
                            title = paste(c("6-4", titleCaseFiltering, titleCaseMismatchType,
                                            "Read Length Freq", repNames[i]), collapse = ' '))
}
```


```{r read_mismatch_position_statistics}
CPDGroupedStats = list(rep1 = list(three_prime = NULL, five_prime = NULL),
                       rep2 = list(three_prime = NULL, five_prime = NULL),
                       all_reps = list(three_prime = NULL, five_prime = NULL))
for (i in seq_along(CPDGroupedStats)) {
  for (j in seq_along(CPDGroupedStats[[i]])) {
    CPDGroupedStats[[i]][[j]] = fread(generateFilePath(
      deaminationSequenceAndPositionDataDirectory, dataTypeStrings$mismatchPositionStats, ".tsv",
      cellType = cellType, lesion = "CPD", repitition = names(CPDGroupedStats)[i],
      strandPolarity = names(CPDGroupedStats[[i]])[j], filtering = filtering, includedMismatches = mismatchType
    ))
  }
}

sixFourGroupedStats = list(rep1 = list(three_prime = NULL, five_prime = NULL),
                           rep2 = list(three_prime = NULL, five_prime = NULL),
                           all_reps = list(three_prime = NULL, five_prime = NULL))
for (i in seq_along(sixFourGroupedStats)) {
  for (j in seq_along(sixFourGroupedStats[[i]])) {
    sixFourGroupedStats[[i]][[j]] = fread(generateFilePath(
      deaminationSequenceAndPositionDataDirectory, dataTypeStrings$mismatchPositionStats, ".tsv",
      cellType = cellType, lesion = "6-4", repitition = names(sixFourGroupedStats)[i],
      strandPolarity = names(sixFourGroupedStats[[i]])[j], filtering = filtering, includedMismatches = mismatchType
    ))
  }
}
```


```{r CPD_position_differences_across_read_lengths, fig.width = 9, fig.height = 5}
for (i in seq_along(CPDGroupedStats)) {
  plotGroupedPositionStats(CPDGroupedStats[[i]]$three_prime, CPDGroupedStats[[i]]$five_prime, POS_DIFF,
                           title = paste(c("CPD", titleCaseFiltering, titleCaseMismatchType,
                                           "Mismatch Pos Diff", repNames[i]), collapse = ' '),
                           xAxisBreaks = c(minReadLength:maxReadLength))
}
```


```{r 6-4_position_differences_across_read_lengths, fig.width = 9, fig.height = 5}
for (i in seq_along(sixFourGroupedStats)) {
  plotGroupedPositionStats(sixFourGroupedStats[[i]]$three_prime, sixFourGroupedStats[[i]]$five_prime, POS_DIFF,
                           title = paste(c("6-4", titleCaseFiltering, titleCaseMismatchType,
                                           "Mismatch Pos Diff", repNames[i]), collapse = ' '),
                           xAxisBreaks = c(minReadLength:maxReadLength))
}
```

EXCISION SITE FIGURE GENERATION STARTS HERE

```{r read_nucleotide_frequency_data}
threePrimeMismatchCPDNucFreq = list(rep1 = NULL, rep2 = NULL, all_reps = NULL)
for (i in seq_along(threePrimeMismatchCPDNucFreq)) {
  threePrimeMismatchCPDNucFreq[[i]] = fread(generateFilePath(
    directory = deaminationExcisionSiteDataDirectory, dataTypeStrings$nucleotideFrequencyData, ".tsv",
    cellType = cellType, lesion = "CPD", repitition = names(threePrimeMismatchCPDNucFreq)[i],
    strandPolarity = "three_prime", anchored = TRUE, filtering = filtering, includedMismatches = mismatchType
  ))
}

fivePrimeMismatchCPDNucFreq = list(rep1 = NULL, rep2 = NULL, all_reps = NULL)
for (i in seq_along(fivePrimeMismatchCPDNucFreq)) {
  fivePrimeMismatchCPDNucFreq[[i]] = fread(generateFilePath(
    directory = deaminationExcisionSiteDataDirectory, dataTypeStrings$nucleotideFrequencyData, ".tsv",
    cellType = cellType, lesion = "CPD", repitition = names(fivePrimeMismatchCPDNucFreq)[i],
    strandPolarity = "five_prime", anchored = TRUE, filtering = filtering, includedMismatches = mismatchType
  ))
}


threePrimeMismatchSixFourNucFreq = list(rep1 = NULL, rep2 = NULL, all_reps = NULL)
for (i in seq_along(threePrimeMismatchSixFourNucFreq)) {
  threePrimeMismatchSixFourNucFreq[[i]] = fread(generateFilePath(
    directory = deaminationExcisionSiteDataDirectory, dataTypeStrings$nucleotideFrequencyData, ".tsv",
    cellType = cellType, lesion = "6-4", repitition = names(threePrimeMismatchSixFourNucFreq)[i],
    strandPolarity = "three_prime", anchored = TRUE, filtering = filtering, includedMismatches = mismatchType
  ))
}

fivePrimeMismatchSixFourNucFreq = list(rep1 = NULL, rep2 = NULL, all_reps = NULL)
for (i in seq_along(fivePrimeMismatchSixFourNucFreq)) {
  fivePrimeMismatchSixFourNucFreq[[i]] = fread(generateFilePath(
    directory = deaminationExcisionSiteDataDirectory, dataTypeStrings$nucleotideFrequencyData, ".tsv",
    cellType = cellType, lesion = "6-4", repitition = names(fivePrimeMismatchSixFourNucFreq)[i],
    strandPolarity = "five_prime", anchored = TRUE, filtering = filtering, includedMismatches = mismatchType
  ))
}
```


```{r CPD_mismatch_anchored_nucleotide_frequencies, fig.width = 11, fig.height = 9}
for (i in seq_along(threePrimeMismatchCPDNucFreq)) {
  plotNucFreqVsReadLengthBarPlot(threePrimeMismatchCPDNucFreq[[i]], 
                                 title = paste(c("CPD", titleCaseFiltering, titleCaseMismatchType,
                                                 "3' Anchored Nuc Freq", repNames[i]), collapse = ' '),
                                 secondaryYAxisLabel = "5' Cut Site Distance", posType = THREE_PRIME,
                                 showFivePrimeCutSite = TRUE, expansionOffset = expansionOffset)
}

for (i in seq_along(fivePrimeMismatchCPDNucFreq)) {
  plotNucFreqVsReadLengthBarPlot(fivePrimeMismatchCPDNucFreq[[i]], 
                                 title = paste(c("CPD", titleCaseFiltering, titleCaseMismatchType,
                                                 "5' Anchored Nuc Freq", repNames[i]), collapse = ' '),
                                 secondaryYAxisLabel = "3' Cut Site Distance", posType = FIVE_PRIME,
                                 showThreePrimeCutSite = TRUE, expansionOffset = expansionOffset)
}
```


```{r CPD_mismatch_anchored_purine_frequencies, fig.width = 11, fig.height = 9}
for (i in seq_along(threePrimeMismatchCPDNucFreq)) {
  plotNucFreqVsReadLengthBarPlot(threePrimeMismatchCPDNucFreq[[i]], 
                                 title = paste(c("CPD", titleCaseFiltering, titleCaseMismatchType,
                                                 "3' Anchored Purine Freq", repNames[i]), collapse = ' '),
                                 yAxisLabel = "Purine Frequency", secondaryYAxisLabel = "5' Cut Site Distance",
                                 combineNucleotides = c("AG"), combinedNames = c("Purine"), posType = THREE_PRIME,
                                 showFivePrimeCutSite = TRUE, expansionOffset = expansionOffset)
}

for (i in seq_along(fivePrimeMismatchCPDNucFreq)) {
  plotNucFreqVsReadLengthBarPlot(fivePrimeMismatchCPDNucFreq[[i]], 
                                 title = paste(c("CPD", titleCaseFiltering, titleCaseMismatchType,
                                                 "5' Anchored Purine Freq", repNames[i]), collapse = ' '),
                                 yAxisLabel = "Purine Frequency", secondaryYAxisLabel = "3' Cut Site Distance",
                                 combineNucleotides = c("AG"), combinedNames = c("Purine"), posType = FIVE_PRIME,
                                 showThreePrimeCutSite = TRUE, expansionOffset = expansionOffset)
}
```


```{r 6-4_mismatch_anchored_nucleotide_frequencies, fig.width = 11, fig.height = 9}
for (i in seq_along(threePrimeMismatchSixFourNucFreq)) {
  plotNucFreqVsReadLengthBarPlot(threePrimeMismatchSixFourNucFreq[[i]], 
                                 title = paste(c("6-4", titleCaseFiltering, titleCaseMismatchType,
                                                 "3' Anchored Nuc Freq", repNames[i]), collapse = ' '),
                                 secondaryYAxisLabel = "5' Cut Site Distance", posType = THREE_PRIME,
                                 showFivePrimeCutSite = TRUE, expansionOffset = expansionOffset)
}

for (i in seq_along(fivePrimeMismatchSixFourNucFreq)) {
  plotNucFreqVsReadLengthBarPlot(fivePrimeMismatchSixFourNucFreq[[i]], 
                                 title = paste(c("6-4", titleCaseFiltering, titleCaseMismatchType,
                                                 "5' Anchored Nuc Freq", repNames[i]), collapse = ' '),
                                 secondaryYAxisLabel = "3' Cut Site Distance", posType = FIVE_PRIME,
                                 showThreePrimeCutSite = TRUE, expansionOffset = expansionOffset)
}
```


```{r 6-4_mismatch_anchored_purine_frequencies, fig.width = 11, fig.height = 9}
for (i in seq_along(threePrimeMismatchSixFourNucFreq)) {
  plotNucFreqVsReadLengthBarPlot(threePrimeMismatchSixFourNucFreq[[i]], 
                                 title = paste(c("6-4", titleCaseFiltering, titleCaseMismatchType,
                                                 "3' Anchored Purine Freq", repNames[i]), collapse = ' '),
                                 yAxisLabel = "Purine Frequency", secondaryYAxisLabel = "5' Cut Site Distance",
                                 combineNucleotides = c("AG"), combinedNames = c("Purine"), posType = THREE_PRIME,
                                 showFivePrimeCutSite = TRUE, expansionOffset = expansionOffset)
}

for (i in seq_along(fivePrimeMismatchSixFourNucFreq)) {
  plotNucFreqVsReadLengthBarPlot(fivePrimeMismatchSixFourNucFreq[[i]], 
                                 title = paste(c("6-4", titleCaseFiltering, titleCaseMismatchType,
                                                 "5' Anchored Purine Freq", repNames[i]), collapse = ' '),
                                 yAxisLabel = "Purine Frequency", secondaryYAxisLabel = "3' Cut Site Distance",
                                 combineNucleotides = c("AG"), combinedNames = c("Purine"), posType = FIVE_PRIME,
                                 showThreePrimeCutSite = TRUE, expansionOffset = expansionOffset)
}
```


```{r read_sequence_frequency_data}
threePrimeMMAnchoredCPDSeqFreq = list(rep1 = CPDTimepoints, rep2 = CPDTimepoints, all_reps = CPDTimepoints)
for (i in seq_along(threePrimeMMAnchoredCPDSeqFreq)) {
  for (j in seq_along(threePrimeMMAnchoredCPDSeqFreq[[i]])) {
    threePrimeMMAnchoredCPDSeqFreq[[i]][[j]] = fread(generateFilePath(
      directory = deaminationExcisionSiteDataDirectory, dataTypeStrings$sequenceFrequency, ".tsv",
      cellType = cellType, lesion = "CPD", repitition = names(threePrimeMMAnchoredCPDSeqFreq)[i],
      timepoint = names(threePrimeMMAnchoredCPDSeqFreq[[i]])[j], strandPolarity = "three_prime",
      anchored = TRUE, sequence = "YR", filtering = filtering, includedMismatches = mismatchType
    ))
  }
}

fivePrimeMMAnchoredCPDSeqFreq = list(rep1 = CPDTimepoints, rep2 = CPDTimepoints, all_reps = CPDTimepoints)
for (i in seq_along(fivePrimeMMAnchoredCPDSeqFreq)) {
  for (j in seq_along(fivePrimeMMAnchoredCPDSeqFreq[[i]])) {
    fivePrimeMMAnchoredCPDSeqFreq[[i]][[j]] = fread(generateFilePath(
      directory = deaminationExcisionSiteDataDirectory, dataTypeStrings$sequenceFrequency, ".tsv",
      cellType = cellType, lesion = "CPD", repitition = names(fivePrimeMMAnchoredCPDSeqFreq)[i],
      timepoint = names(fivePrimeMMAnchoredCPDSeqFreq[[i]])[j], strandPolarity = "five_prime",
      anchored = TRUE, sequence = "TGG", filtering = filtering, includedMismatches = mismatchType
    ))
  }
}


threePrimeMMAnchoredSixFourSeqFreq = list(rep1 = sixFourTimepoints, rep2 = sixFourTimepoints,
                                          all_reps = sixFourTimepoints)
for (i in seq_along(threePrimeMMAnchoredSixFourSeqFreq)) {
  for (j in seq_along(threePrimeMMAnchoredSixFourSeqFreq[[i]])) {
    threePrimeMMAnchoredSixFourSeqFreq[[i]][[j]] = fread(generateFilePath(
      directory = deaminationExcisionSiteDataDirectory, dataTypeStrings$sequenceFrequency, ".tsv",
      cellType = cellType, lesion = "6-4", repitition = names(threePrimeMMAnchoredSixFourSeqFreq)[i],
      timepoint = names(threePrimeMMAnchoredSixFourSeqFreq[[i]])[j], strandPolarity = "three_prime",
      anchored = TRUE, sequence = "YR", filtering = filtering, includedMismatches = mismatchType
    ))
  }
}

fivePrimeMMAnchoredSixFourSeqFreq = list(rep1 = sixFourTimepoints, rep2 = sixFourTimepoints,
                                         all_reps = sixFourTimepoints)
for (i in seq_along(fivePrimeMMAnchoredSixFourSeqFreq)) {
  for (j in seq_along(fivePrimeMMAnchoredSixFourSeqFreq[[i]])) {
    fivePrimeMMAnchoredSixFourSeqFreq[[i]][[j]] = fread(generateFilePath(
      directory = deaminationExcisionSiteDataDirectory, dataTypeStrings$sequenceFrequency, ".tsv",
      cellType = cellType, lesion = "6-4", repitition = names(fivePrimeMMAnchoredSixFourSeqFreq)[i],
      timepoint = names(fivePrimeMMAnchoredSixFourSeqFreq[[i]])[j], strandPolarity = "five_prime",
      anchored = TRUE, sequence = "TGG", filtering = filtering, includedMismatches = mismatchType
    ))
  }
}
```


```{r CPD_sequence_frequencies, fig.width = 11, fig.height = 9}
for (i in seq_along(threePrimeMMAnchoredCPDSeqFreq)) {
  plotSequenceFrequencies(threePrimeMMAnchoredCPDSeqFreq[[i]],
                          title = paste(c("CPD", titleCaseFiltering, titleCaseMismatchType,
                                          "3' Anchored YR Freq", repNames[i]), collapse = ' '),
                          secondaryYAxisLabel = "5' Cut Site Distance", showFivePrimeCutSite = TRUE,
                          expansionOffset = expansionOffset, querySequences = c("CG","CA","TG","TA"))
}

for (i in seq_along(fivePrimeMMAnchoredCPDSeqFreq)) {
  plotSequenceFrequencies(fivePrimeMMAnchoredCPDSeqFreq[[i]],
                          title = paste(c("CPD", titleCaseFiltering, titleCaseMismatchType,
                                          "5' Anchored TGG Freq", repNames[i]), collapse = ' '),
                          secondaryYAxisLabel = "3' Cut Site Distance", showThreePrimeCutSite = TRUE,
                          expansionOffset = expansionOffset, posType = FIVE_PRIME, querySequences = c("TGG"))
}
```


```{r 6-4_sequence_frequencies, fig.width = 11, fig.height = 9}
for (i in seq_along(threePrimeMMAnchoredSixFourSeqFreq)) {
  plotSequenceFrequencies(threePrimeMMAnchoredSixFourSeqFreq[[i]],
                          title = paste(c("6-4", titleCaseFiltering, titleCaseMismatchType,
                                          "3' Anchored YR Freq", repNames[i]), collapse = ' '),
                          secondaryYAxisLabel = "5' Cut Site Distance", showFivePrimeCutSite = TRUE,
                          expansionOffset = expansionOffset, querySequences = c("CG","CA","TG","TA"))
}

for (i in seq_along(fivePrimeMMAnchoredSixFourSeqFreq)) {
  plotSequenceFrequencies(fivePrimeMMAnchoredSixFourSeqFreq[[i]],
                          title = paste(c("6-4", titleCaseFiltering, titleCaseMismatchType,
                                          "5' Anchored TGG Freq", repNames[i]), collapse = ' '),
                          secondaryYAxisLabel = "3' Cut Site Distance", showThreePrimeCutSite = TRUE,
                          expansionOffset = expansionOffset, posType = FIVE_PRIME, querySequences = c("TGG"))
}
```

