---
title: "5'CutSiteAnalysisDataGeneration"
author: "Ben MOrledge-Hampton"
date: '2022-07-14'
output: html_document
params:
  bioinformaticsDirectory:
    label: "Bioinformatics Projects Directory"
    value: C:/Bioinformatics_Projects
    input: select
    choices: [C:/Bioinformatics_Projects, F:/Bioinformatics_Projects]
---


```{r setup_chunk}
library(knitr)
library(stringr)

expansionOffset = 10
filtering = "TGG_filtered"

if (interactive()) {
  bioinformaticsDirectory = choose.dir(caption = "Select Bioinformatics_Projects Directory")
} else {
  bioinformaticsDirectory = params$bioinformaticsDirectory
}

if (is.na(bioinformaticsDirectory)) stop("No bioinformatics directory given.")

deaminationDataDirectory = file.path(bioinformaticsDirectory, "deamination_determination", "data")
NHF1MismatchesByReadDirectory = file.path(deaminationDataDirectory, "NHF1", "mismatches_by_read")
NHF1CutSiteCorrelationDirectory = file.path(deaminationDataDirectory, "NHF1", "cut_site_correlation")
arabidopsisMismatchesByReadDirectory = file.path(deaminationDataDirectory, "Arabidopsis", "mismatches_by_read")
arabidopsisCutSiteCorrelationDirectory = file.path(deaminationDataDirectory, "Arabidopsis", "cut_site_correlation")
yeastMismatchesByReadDirectory = file.path(deaminationDataDirectory, "yeast", "mismatches_by_read")
yeastCutSiteCorrelationDirectory = file.path(deaminationDataDirectory, "yeast", "cut_site_correlation")
dir.create(NHF1CutSiteCorrelationDirectory, showWarnings = FALSE, recursive = TRUE)
dir.create(arabidopsisCutSiteCorrelationDirectory, showWarnings = FALSE, recursive = TRUE)
dir.create(yeastCutSiteCorrelationDirectory, showWarnings = FALSE, recursive = TRUE)
```


```{r source_functions}
source(file.path(bioinformaticsDirectory, "deamination_determination", 'R',
                 "UsefulFileSystemFunctions.R"))
source(file.path(bioinformaticsDirectory, "deamination_determination", 'R',
                 "CutSiteCorrelationAnalysis.R"))
```


```{r define_all_that_and_a_bag_of_chips_function}
cutSiteCorrelationAnalysisDataGeneration = function(lesion, repetition, timepoint, cellType, inputDirectory, outputDirectory,
                                                    includedMismatches = character(), omittedMismatches = character(),
                                                    filteredAndFormattedInput = TRUE,
                                                    filePathIncludedMismatches = NULL, filePathOmittedMismatches = NULL) {
  
  if (is.null(filePathIncludedMismatches)) {
    filePathIncludedMismatches = includedMismatches
  }
  if (is.null(filePathOmittedMismatches)) {
    filePathOmittedMismatches = omittedMismatches
  }
  
  if (filteredAndFormattedInput) {
    inputType = dataTypeStrings$mismatchesByReadRelationFormatted
  } else {
    inputType = dataTypeStrings$mismatchesByRead
  }
  
  mismatchesByRead = fread(generateFilePath(
    inputDirectory, inputType, ".bed",
    cellType = cellType, lesion = lesion, timepoint = timepoint,
    repitition = repetition, filtering = filtering,
    includedMismatches = filePathIncludedMismatches, omittedMismatches = filePathOmittedMismatches
  ))
  
  if (filteredAndFormattedInput) {
    additionalInformation = character()
  } else {
    additionalInformation = "minimal_filtering"
  }
  
  if (!filteredAndFormattedInput) {mismatchesByRead = mismatchesByRead[str_count(V5, ':') == 0]}
  
  if (length(filePathIncludedMismatches) != length(includedMismatches)) {
    mismatchesByRead = mismatchesByRead[V5 %in% includedMismatches]
    mismatchesByRead[,V4:=as.numeric(V4)]
  } else if (length(filePathOmittedMismatches) != length(omittedMismatches)) {
    mismatchesByRead = mismatchesByRead[!V5 %in% omittedMismatches]
    mismatchesByRead[,V4:=as.numeric(V4)]
  }
  
  fwrite(getPairedCutSiteDistances(mismatchesByRead, filteredAndFormattedInput), sep = '\t', file = generateFilePath(
    outputDirectory, dataTypeStrings$pairedCutSiteDistances , ".tsv",
    cellType = cellType, lesion = lesion, timepoint = timepoint,
    repitition = repetition, filtering = filtering,
    includedMismatches = includedMismatches, omittedMismatches = omittedMismatches,
    additionalInformation = additionalInformation
  ))
  
}
```


```{r generate_cut_site_correlation_data}
cutSiteCorrelationAnalysisDataGeneration("CPD", "all_reps", "1h", "NHF1",
                                         NHF1MismatchesByReadDirectory, NHF1CutSiteCorrelationDirectory,
                                         includedMismatches = "CC>TT")
cutSiteCorrelationAnalysisDataGeneration("CPD", "all_reps", "1h", "NHF1",
                                         NHF1MismatchesByReadDirectory, NHF1CutSiteCorrelationDirectory,
                                         includedMismatches = "C>T")
cutSiteCorrelationAnalysisDataGeneration("CPD", "all_reps", "1h", "NHF1",
                                         NHF1MismatchesByReadDirectory, NHF1CutSiteCorrelationDirectory,
                                         omittedMismatches = "C>T")
cutSiteCorrelationAnalysisDataGeneration("CPD", "all_reps", "1h", "NHF1",
                                         NHF1MismatchesByReadDirectory, NHF1CutSiteCorrelationDirectory,
                                         includedMismatches = "CC>TT", filteredAndFormattedInput = FALSE)
cutSiteCorrelationAnalysisDataGeneration("CPD", "all_reps", "1h", "NHF1",
                                         NHF1MismatchesByReadDirectory, NHF1CutSiteCorrelationDirectory,
                                         includedMismatches = "C>T", filteredAndFormattedInput = FALSE,
                                         filePathIncludedMismatches = character())
cutSiteCorrelationAnalysisDataGeneration("CPD", "all_reps", "1h", "NHF1",
                                         NHF1MismatchesByReadDirectory, NHF1CutSiteCorrelationDirectory,
                                         omittedMismatches = "C>T", filteredAndFormattedInput = FALSE,
                                         filePathOmittedMismatches = character())

cutSiteCorrelationAnalysisDataGeneration("CPD", "all_reps", "8h", "NHF1",
                                         NHF1MismatchesByReadDirectory, NHF1CutSiteCorrelationDirectory,
                                         includedMismatches = "CC>TT")
cutSiteCorrelationAnalysisDataGeneration("CPD", "all_reps", "8h", "NHF1",
                                         NHF1MismatchesByReadDirectory, NHF1CutSiteCorrelationDirectory,
                                         includedMismatches = "C>T")
cutSiteCorrelationAnalysisDataGeneration("CPD", "all_reps", "8h", "NHF1",
                                         NHF1MismatchesByReadDirectory, NHF1CutSiteCorrelationDirectory,
                                         omittedMismatches = "C>T")

cutSiteCorrelationAnalysisDataGeneration("CPD", "all_reps", "ZT2", "Arabidopsis",
                                         arabidopsisMismatchesByReadDirectory, arabidopsisCutSiteCorrelationDirectory,
                                         includedMismatches = "CC>TT")
cutSiteCorrelationAnalysisDataGeneration("CPD", "all_reps", "ZT2", "Arabidopsis",
                                         arabidopsisMismatchesByReadDirectory, arabidopsisCutSiteCorrelationDirectory,
                                         includedMismatches = "C>T")
cutSiteCorrelationAnalysisDataGeneration("CPD", "all_reps", "ZT2", "Arabidopsis",
                                         arabidopsisMismatchesByReadDirectory, arabidopsisCutSiteCorrelationDirectory,
                                         omittedMismatches = "C>T")


cutSiteCorrelationAnalysisDataGeneration("CPD", "all_reps", "20min", "yeast",
                                         yeastMismatchesByReadDirectory, yeastCutSiteCorrelationDirectory,
                                         includedMismatches = "CC>TT")
cutSiteCorrelationAnalysisDataGeneration("CPD", "all_reps", "20min", "yeast",
                                         yeastMismatchesByReadDirectory, yeastCutSiteCorrelationDirectory,
                                         includedMismatches = "C>T")
cutSiteCorrelationAnalysisDataGeneration("CPD", "all_reps", "20min", "yeast",
                                         yeastMismatchesByReadDirectory, yeastCutSiteCorrelationDirectory,
                                         omittedMismatches = "C>T")

```

