---
title: "5'CutSiteAnalysisDataGeneration"
author: "Ben MOrledge-Hampton"
date: '2022-07-14'
output: html_document
params:
  bioinformaticsDirectory:
    label: "Bioinformatics Projects Directory"
    value: C:/Bioinformatics_Projects
    input: select
    choices: [C:/Bioinformatics_Projects, F:/Bioinformatics_Projects]
---


```{r setup_chunk}
library(knitr)

expansionOffset = 10
filtering = "TGG_filtered"

if (interactive()) {
  bioinformaticsDirectory = choose.dir(caption = "Select Bioinformatics_Projects Directory")
} else {
  bioinformaticsDirectory = params$bioinformaticsDirectory
}

if (is.na(bioinformaticsDirectory)) stop("No bioinformatics directory given.")

opts_chunk$set(dev = "png", dpi = 600, fig.width = 7, fig.height = 5, 
               fig.path = paste0(file.path("deamination_analysis_output","combined",
                                           paste(c(filtering,"correlation_analysis"), collapse = '_')),
                                 .Platform$file.sep))

deaminationDataDirectory = file.path(bioinformaticsDirectory, "deamination_determination", "data")
NHF1CutSiteCorrelationDirectory = file.path(deaminationDataDirectory, "NHF1", "cut_site_correlation")
arabidopsisCutSiteCorrelationDirectory = file.path(deaminationDataDirectory, "Arabidopsis", "cut_site_correlation")
yeastCutSiteCorrelationDirectory = file.path(deaminationDataDirectory, "yeast", "cut_site_correlation")
eColiCutSiteCorrelationDirectory = file.path(deaminationDataDirectory, "E_coli_WT", "cut_site_correlation")
```


```{r source_functions}
source(file.path(bioinformaticsDirectory, "deamination_determination", 'R',
                 "UsefulFileSystemFunctions.R"))
source(file.path(bioinformaticsDirectory, "deamination_determination", 'R',
                 "CutSiteCorrelationAnalysis.R"))
```


```{r define_all_that_and_a_bag_of_chips_function}
cutSiteCorrelationAnalysisFigureGeneration = function(lesion, repetition, timepoint, cellType, directory,
                                                      includedMismatches = character(), omittedMismatches = character(),
                                                      filteredAndFormattedInput = TRUE, noPositionFiltering = FALSE,
                                                      atypicalPositionFiltering = FALSE,
                                                      shuffle = FALSE) {

  if (filteredAndFormattedInput) {
    if (noPositionFiltering) {
      additionalInformation = "no_position_filtering"
    } else if (atypicalPositionFiltering) {
      additionalInformation = "atypical_position_filtering"
    } else {
      additionalInformation = character()
    }
  } else {
    additionalInformation = "minimal_filtering"
  }

  pairedCutSiteDistances = fread(generateFilePath(
    directory, dataTypeStrings$pairedCutSiteDistances , ".tsv",
    cellType = cellType, lesion = lesion, timepoint = timepoint,
    repitition = repetition, filtering = filtering,
    includedMismatches = includedMismatches, omittedMismatches = omittedMismatches,
    additionalInformation = additionalInformation
  ))
  
  if (shuffle) {
    pairedCutSiteDistances = getShufflePairedCutSiteDistances(pairedCutSiteDistances)
    additionalInformation = paste(additionalInformation,"5'_shuffled")
  }
  
  if (length(includedMismatches) > 0) {
    mismatchText = includedMismatches
  } else if (length(omittedMismatches) > 0) {
    mismatchText = paste0("non-",paste(omittedMismatches,collapse = '-'))
  } else {
    mismatchText = ''
  }
  
  print(paste(cellType, lesion, timepoint, mismatchText, additionalInformation))
  
  print("  3' cut site model:")
  correlationResults = getCorrelationResults(pairedCutSiteDistances, THREE_PRIME_CUT_SITE_DISTANCE)
  print(paste0("    r = ",correlationResults$estimate, "; p = ",correlationResults$p.value))
  linearModel = lm(Three_Prime_Cut_Site_Distance ~ Five_Prime_Cut_Site_Distance, pairedCutSiteDistances)
  print(paste0("    Slope = ",linearModel$coefficients[2], "; p = ", summary(linearModel)$coefficients[8]))
  
  plotPairedCutSiteDistances(pairedCutSiteDistances, THREE_PRIME_CUT_SITE_DISTANCE,
                             title = paste(cellType, lesion, timepoint, mismatchText,
                                           "Cut Site Correlation", additionalInformation))
  
  print("  Read length model:")
  correlationResults = getCorrelationResults(pairedCutSiteDistances, READ_LENGTH)
  print(paste0("    r = ",correlationResults$estimate, "; p = ",correlationResults$p.value))
  linearModel = lm(Read_Length ~ Five_Prime_Cut_Site_Distance, pairedCutSiteDistances)
  print(paste0("    Slope = ",linearModel$coefficients[2], "; p = ", summary(linearModel)$coefficients[8]))
  
  plotPairedCutSiteDistances(pairedCutSiteDistances, READ_LENGTH,
                             title = paste(cellType, lesion, timepoint, mismatchText,
                                           "Cut Site Correlation", additionalInformation))
}
```


```{r NHF1_1h_cut_site_correlation_figures}
cutSiteCorrelationAnalysisFigureGeneration("CPD", "all_reps", "1h", "NHF1", NHF1CutSiteCorrelationDirectory,
                                           includedMismatches = "CC>TT")
cutSiteCorrelationAnalysisFigureGeneration("CPD", "all_reps", "1h", "NHF1", NHF1CutSiteCorrelationDirectory,
                                           includedMismatches = "C>T")
cutSiteCorrelationAnalysisFigureGeneration("CPD", "all_reps", "1h", "NHF1", NHF1CutSiteCorrelationDirectory,
                                           omittedMismatches = "C>T")

cutSiteCorrelationAnalysisFigureGeneration("CPD", "all_reps", "1h", "NHF1", NHF1CutSiteCorrelationDirectory,
                                           includedMismatches = "CC>TT", shuffle = TRUE)
cutSiteCorrelationAnalysisFigureGeneration("CPD", "all_reps", "1h", "NHF1", NHF1CutSiteCorrelationDirectory,
                                           includedMismatches = "C>T", shuffle = TRUE)
cutSiteCorrelationAnalysisFigureGeneration("CPD", "all_reps", "1h", "NHF1", NHF1CutSiteCorrelationDirectory,
                                           omittedMismatches = "C>T", shuffle = TRUE)

cutSiteCorrelationAnalysisFigureGeneration("CPD", "all_reps", "1h", "NHF1", NHF1CutSiteCorrelationDirectory,
                                           includedMismatches = "CC>TT", filteredAndFormattedInput = FALSE)
cutSiteCorrelationAnalysisFigureGeneration("CPD", "all_reps", "1h", "NHF1", NHF1CutSiteCorrelationDirectory,
                                           includedMismatches = "C>T", filteredAndFormattedInput = FALSE)
cutSiteCorrelationAnalysisFigureGeneration("CPD", "all_reps", "1h", "NHF1", NHF1CutSiteCorrelationDirectory,
                                           omittedMismatches = "C>T", filteredAndFormattedInput = FALSE)

cutSiteCorrelationAnalysisFigureGeneration("CPD", "all_reps", "1h", "NHF1", NHF1CutSiteCorrelationDirectory,
                                           includedMismatches = "CC>TT", noPositionFiltering = TRUE)
cutSiteCorrelationAnalysisFigureGeneration("CPD", "all_reps", "1h", "NHF1", NHF1CutSiteCorrelationDirectory,
                                           includedMismatches = "C>T", noPositionFiltering = TRUE)
cutSiteCorrelationAnalysisFigureGeneration("CPD", "all_reps", "1h", "NHF1", NHF1CutSiteCorrelationDirectory,
                                           omittedMismatches = "C>T", atypicalPositionFiltering = TRUE)
```


```{r NHF1_8h_cut_site_correlation_figures}
cutSiteCorrelationAnalysisFigureGeneration("CPD", "all_reps", "8h", "NHF1", NHF1CutSiteCorrelationDirectory,
                                           includedMismatches = "CC>TT")
cutSiteCorrelationAnalysisFigureGeneration("CPD", "all_reps", "8h", "NHF1", NHF1CutSiteCorrelationDirectory,
                                           includedMismatches = "C>T")
cutSiteCorrelationAnalysisFigureGeneration("CPD", "all_reps", "8h", "NHF1", NHF1CutSiteCorrelationDirectory,
                                           omittedMismatches = "C>T")

cutSiteCorrelationAnalysisFigureGeneration("CPD", "all_reps", "8h", "NHF1", NHF1CutSiteCorrelationDirectory,
                                           includedMismatches = "CC>TT", shuffle = TRUE)
cutSiteCorrelationAnalysisFigureGeneration("CPD", "all_reps", "8h", "NHF1", NHF1CutSiteCorrelationDirectory,
                                           includedMismatches = "C>T", shuffle = TRUE)
cutSiteCorrelationAnalysisFigureGeneration("CPD", "all_reps", "8h", "NHF1", NHF1CutSiteCorrelationDirectory,
                                           omittedMismatches = "C>T", shuffle = TRUE)
```


```{r Arabidopsis_cut_site_correlation_figures}
cutSiteCorrelationAnalysisFigureGeneration("CPD", "all_reps", "ZT2", "Arabidopsis", arabidopsisCutSiteCorrelationDirectory,
                                           includedMismatches = "CC>TT")
cutSiteCorrelationAnalysisFigureGeneration("CPD", "all_reps", "ZT2", "Arabidopsis", arabidopsisCutSiteCorrelationDirectory,
                                           includedMismatches = "C>T")
cutSiteCorrelationAnalysisFigureGeneration("CPD", "all_reps", "ZT2", "Arabidopsis", arabidopsisCutSiteCorrelationDirectory,
                                           omittedMismatches = "C>T")

cutSiteCorrelationAnalysisFigureGeneration("CPD", "all_reps", "ZT2", "Arabidopsis", arabidopsisCutSiteCorrelationDirectory,
                                           includedMismatches = "CC>TT", shuffle = TRUE)
cutSiteCorrelationAnalysisFigureGeneration("CPD", "all_reps", "ZT2", "Arabidopsis", arabidopsisCutSiteCorrelationDirectory,
                                           includedMismatches = "C>T", shuffle = TRUE)
cutSiteCorrelationAnalysisFigureGeneration("CPD", "all_reps", "ZT2", "Arabidopsis", arabidopsisCutSiteCorrelationDirectory,
                                           omittedMismatches = "C>T", shuffle = TRUE)
```


```{r yeast_cut_site_correlation_figures}
cutSiteCorrelationAnalysisFigureGeneration("CPD", "all_reps", "20min", "yeast", yeastCutSiteCorrelationDirectory,
                                           includedMismatches = "CC>TT")
cutSiteCorrelationAnalysisFigureGeneration("CPD", "all_reps", "20min", "yeast", yeastCutSiteCorrelationDirectory,
                                           includedMismatches = "C>T")
cutSiteCorrelationAnalysisFigureGeneration("CPD", "all_reps", "20min", "yeast", yeastCutSiteCorrelationDirectory,
                                           omittedMismatches = "C>T")

cutSiteCorrelationAnalysisFigureGeneration("CPD", "all_reps", "20min", "yeast", yeastCutSiteCorrelationDirectory,
                                           includedMismatches = "CC>TT", shuffle = TRUE)
cutSiteCorrelationAnalysisFigureGeneration("CPD", "all_reps", "20min", "yeast", yeastCutSiteCorrelationDirectory,
                                           includedMismatches = "C>T", shuffle = TRUE)
cutSiteCorrelationAnalysisFigureGeneration("CPD", "all_reps", "20min", "yeast", yeastCutSiteCorrelationDirectory,
                                           omittedMismatches = "C>T", shuffle = TRUE)
```


```{r E_coli_cut_site_correlation_figures}
cutSiteCorrelationAnalysisFigureGeneration("CPD", "all_reps", "5min", "E_coli_WT", eColiCutSiteCorrelationDirectory,
                                           includedMismatches = "CC>TT", noPositionFiltering = TRUE)
cutSiteCorrelationAnalysisFigureGeneration("CPD", "all_reps", "5min", "E_coli_WT", eColiCutSiteCorrelationDirectory,
                                           includedMismatches = "C>T", noPositionFiltering = TRUE)
cutSiteCorrelationAnalysisFigureGeneration("CPD", "all_reps", "5min", "E_coli_WT", eColiCutSiteCorrelationDirectory,
                                           omittedMismatches = "C>T")
```
