---
title: "R Notebook"
output: html_document
params:
  bioinformaticsDirectory:
    label: "Bioinformatics Projects Directory"
    value: C:/Bioinformatics_Projects
    input: select
    choices: [C:/Bioinformatics_Projects, F:/Bioinformatics_Projects]
---


```{r setup_chunk}
library(knitr)
opts_chunk$set(dev = "png", dpi = 600, fig.width = 7, fig.height = 5)
if (interactive()) {
  bioinformaticsDirectory = choose.dir(caption = "Select Bioinformatics_Projects Directory")
} else {
  bioinformaticsDirectory = params$bioinformaticsDirectory
}
```


```{r source_functions}
source(file.path(bioinformaticsDirectory, "deamination_determination", 'R', "DeaminationAnalysis.R"))
source(file.path(bioinformaticsDirectory, "Chromatin_Features_Analysis", "R_scripts", "PeriodicityAnalysis.R"))
```



```{r acquire_and_format_data_1}
deaminationDataDirectory = file.path(bioinformaticsDirectory, "deamination_determination", "data")

# Read in the relevant data
CPDMismatchDataFilePaths = list(rep1 = list(), rep2 = list())
CPDMismatchDataFilePaths$rep1 = list(
  hr1 = file.path(deaminationDataDirectory, "NHF1_CPD_1h_Rep1_mismatches.bed"),
  hr8 = file.path(deaminationDataDirectory, "NHF1_CPD_8h_Rep1_mismatches.bed"),
  hr24 = file.path(deaminationDataDirectory, "NHF1_CPD_24h_Rep1_mismatches.bed"),
  hr48 = file.path(deaminationDataDirectory, "NHF1_CPD_48h_Rep1_mismatches.bed")
)
CPDMismatchDataFilePaths$rep2 = list(
  hr1 = file.path(deaminationDataDirectory, "NHF1_CPD_1h_Rep2_mismatches.bed"),
  hr8 = file.path(deaminationDataDirectory, "NHF1_CPD_8h_Rep2_mismatches.bed"),
  hr24 = file.path(deaminationDataDirectory, "NHF1_CPD_24h_Rep2_mismatches.bed"),
  hr48 = file.path(deaminationDataDirectory, "NHF1_CPD_48h_Rep2_mismatches.bed")
)

sixFourMismatchDataFilePaths = list(rep1 = list(), rep2 = list())
sixFourMismatchDataFilePaths$rep1 = list(
  min5 = file.path(deaminationDataDirectory, "NHF1_6-4-PP_5min_Rep1_mismatches.bed"),
  min20 = file.path(deaminationDataDirectory, "NHF1_6-4-PP_20min_Rep1_mismatches.bed"),
  hr1 = file.path(deaminationDataDirectory, "NHF1_6-4-PP_1h_Rep1_mismatches.bed")
)
sixFourMismatchDataFilePaths$rep2 = list(
  min5 = file.path(deaminationDataDirectory, "NHF1_6-4-PP_5min_Rep2_mismatches.bed"),
  min20 = file.path(deaminationDataDirectory, "NHF1_6-4-PP_20min_Rep2_mismatches.bed"),
  hr1 = file.path(deaminationDataDirectory, "NHF1_6-4-PP_1h_Rep2_mismatches.bed")
)

CPDMismatchData = lapply(CPDMismatchDataFilePaths, function(x) lapply(x, fread))
sixFourMismatchData = lapply(sixFourMismatchDataFilePaths, function(x) lapply(x, fread))

# Filter the data
CPDMismatchData = lapply(CPDMismatchData, function(x) lapply(
  x, function(y) filterResults(y, TRUE, 3, 23, 31)
))
sixFourMismatchData = lapply(sixFourMismatchData, function(x) lapply(
  x, function(y) filterResults(y, TRUE, 3, 23, 31)
))

# Extract and simplify tandem C>T mismatches
CPDTandemCTMismatches = lapply(CPDMismatchData, function(x) lapply(
  x, function(y) simplifyTable(getTandemCTMismatches(y))
))
sixFourTandemCTMismatches = lapply(sixFourMismatchData, function(x) lapply(
  x, function(y) simplifyTable(getTandemCTMismatches(y))
))

# Simplify the data
CPDMismatchData = lapply(CPDMismatchData, function(x) lapply(
  x, function(y) simplifyTable(y)
))
sixFourMismatchData = lapply(sixFourMismatchData, function(x) lapply(
  x, function(y) simplifyTable(y)
))

```


```{r plot_CPD_mismatch_type_frequency}
for (i in 1:length(CPDMismatchData)) {
  for (j in 1:length(CPDMismatchData[[i]])) {
    plotMismatchTypeFrequencies(CPDMismatchData[[i]][[j]],
                                title = paste("CPD", names(CPDMismatchData)[i], 
                                              names(CPDMismatchData[[i]])[j], "Mismatch Type Frequency"))
  }
}
```


```{r plot_6-4_mismatch_type_frequency}
for (i in 1:length(sixFourMismatchData)) {
  for (j in 1:length(sixFourMismatchData[[i]])) {
    plotMismatchTypeFrequencies(sixFourMismatchData[[i]][[j]],
                                title = paste("6-4", names(sixFourMismatchData)[i], 
                                              names(sixFourMismatchData[[i]])[j], "Mismatch Type Frequency"))
  }
}

```


```{r plot_CPD_mismatch_pos_frequency}
for (i in 1:length(CPDMismatchData)) {
  for (j in 1:length(CPDMismatchData[[i]])) {
    plotMismatchPositionFrequencies(CPDMismatchData[[i]][[j]], includedTypes = c("C>T"),
                                    title = paste("CPD", names(CPDMismatchData)[i], 
                                                  names(CPDMismatchData[[i]])[j], "C>T Mismatch Positions"))
    plotMismatchPositionFrequencies(CPDMismatchData[[i]][[j]], omittedTypes = c("C>T"),
                                    title = paste("CPD", names(CPDMismatchData)[i], 
                                                  names(CPDMismatchData[[i]])[j], "!C>T Mismatch Positions"))
  }
}
```


```{r plot_6-4_mismatch_pos_frequency}
for (i in 1:length(sixFourMismatchData)) {
  for (j in 1:length(sixFourMismatchData[[i]])) {
    plotMismatchPositionFrequencies(sixFourMismatchData[[i]][[j]], includedTypes = c("C>T"),
                                    title = paste("6-4", names(sixFourMismatchData)[i], 
                                                  names(sixFourMismatchData[[i]])[j], "C>T Mismatch Positions"))
    plotMismatchPositionFrequencies(sixFourMismatchData[[i]][[j]], omittedTypes = c("C>T"),
                                    title = paste("6-4", names(sixFourMismatchData)[i], 
                                                  names(sixFourMismatchData[[i]])[j], "!C>T Mismatch Positions"))
  }
}

```


```{r plot_CPD_tandem_C>T_pos_frequency}
for (i in 1:length(CPDTandemCTMismatches)) {
  for (j in 1:length(CPDTandemCTMismatches[[i]])) {
    plotMismatchPositionFrequencies(CPDTandemCTMismatches[[i]][[j]],
                                    title = paste("CPD", names(CPDTandemCTMismatches)[i], 
                                                  names(CPDTandemCTMismatches[[i]])[j], "Tandem C>T Mismatch Pos"))
  }
}
```


```{r plot_6-4_tandem_C>T_pos_frequency}
for (i in 1:length(sixFourTandemCTMismatches)) {
  for (j in 1:length(sixFourTandemCTMismatches[[i]])) {
    plotMismatchPositionFrequencies(sixFourTandemCTMismatches[[i]][[j]],
                                    title = paste("6-4", names(sixFourTandemCTMismatches)[i], 
                                                  names(sixFourTandemCTMismatches[[i]])[j], 
                                                  "Tandem C>T Mismatch Pos"))
  }
}
```


```{r acquire_and_format_data_2}
load(file.path(deaminationDataDirectory, "deamination_periodicity_results.rda"))
dataSetNames = as.list(setNames(nm = mutperiodData$periodicityResults$Data_Set))

```


```{r CPD_rotational_periodicity_trinuc_normalized}
parseAndPlotPeriodicity(dataSetNames$NHF1_CPD_1h_Rep1_individual_mismatches_MNase_map_intergenic_trinuc_normalized,
                        title = "CPD 1hr Rep1 Rotational Trinuc Norm")
parseAndPlotPeriodicity(dataSetNames$NHF1_CPD_24h_Rep1_individual_mismatches_MNase_map_intergenic_trinuc_normalized,
                        title = "CPD 24hr Rep1 Rotational Trinuc Norm")
parseAndPlotPeriodicity(dataSetNames$NHF1_CPD_48h_Rep1_individual_mismatches_MNase_map_intergenic_trinuc_normalized,
                        title = "CPD 48hr Rep1 Rotational Trinuc Norm")
```


```{r CPD_rotational_periodicity_XR-seq_normalized}
parseAndPlotPeriodicity(
  dataSetNames$NHF1_CPD_1h_Rep1_individual_mismatches_MNase_map_intergenic_custom_context_normalized,
  title = "CPD 1hr Rep1 Rotational XR-seq Norm")
parseAndPlotPeriodicity(
  dataSetNames$NHF1_CPD_24h_Rep1_individual_mismatches_MNase_map_intergenic_custom_context_normalized,
  title = "CPD 24hr Rep1 Rotational XR-seq Norm")
parseAndPlotPeriodicity(
  dataSetNames$NHF1_CPD_48h_Rep1_individual_mismatches_MNase_map_intergenic_custom_context_normalized,
  title = "CPD 48hr Rep1 Rotational XR-seq Norm")
```


```{r CPD_translational_periodicity_trinuc_normalized}
parseAndPlotPeriodicity(
  dataSetNames$`NHF1_CPD_1h_Rep1_individual_mismatches_MNase_map_intergenic_trinuc_nuc-group_normalized`,
  title = "CPD 1hr Rep1 Rotational Trinuc Norm")
parseAndPlotPeriodicity(
  dataSetNames$`NHF1_CPD_24h_Rep1_individual_mismatches_MNase_map_intergenic_trinuc_nuc-group_normalized`,
  title = "CPD 24hr Rep1 Rotational Trinuc Norm")
parseAndPlotPeriodicity(
  dataSetNames$`NHF1_CPD_48h_Rep1_individual_mismatches_MNase_map_intergenic_trinuc_nuc-group_normalized`,
  title = "CPD 48hr Rep1 Rotational Trinuc Norm")
```



```{r CPD_translational_periodicity_XR-seq_normalized}
parseAndPlotPeriodicity(
  dataSetNames$`NHF1_CPD_1h_Rep1_individual_mismatches_MNase_map_intergenic_custom_context_nuc-group_normalized`,
  title = "CPD 1hr Rep1 Rotational XR-seq Norm")
parseAndPlotPeriodicity(
  dataSetNames$`NHF1_CPD_24h_Rep1_individual_mismatches_MNase_map_intergenic_custom_context_nuc-group_normalized`,
  title = "CPD 24hr Rep1 Rotational XR-seq Norm")
parseAndPlotPeriodicity(
  dataSetNames$`NHF1_CPD_48h_Rep1_individual_mismatches_MNase_map_intergenic_custom_context_nuc-group_normalized`,
  title = "CPD 48hr Rep1 Rotational XR-seq Norm")
```


```{r acquire_and_format_data_3}
load(file.path(deaminationDataDirectory, "TCG_deamination_periodicity_results.rda"))
dataSetNames = as.list(setNames(nm = mutperiodData$periodicityResults$Data_Set))

```


```{r TCG_CPD_rotational_periodicity_trinuc_normalized}
parseAndPlotPeriodicity(
  dataSetNames$TCG_NHF1_CPD_1h_Rep1_individual_mismatches_MNase_map_intergenic_trinuc_normalized,
  title = "TCG CPD 1hr Rep1 Rotational Trinuc Norm")
parseAndPlotPeriodicity(
  dataSetNames$TCG_NHF1_CPD_24h_Rep1_individual_mismatches_MNase_map_intergenic_trinuc_normalized,
  title = "TCG CPD 24hr Rep1 Rotational Trinuc Norm")
parseAndPlotPeriodicity(
  dataSetNames$TCG_NHF1_CPD_48h_Rep1_individual_mismatches_MNase_map_intergenic_trinuc_normalized,
  title = "TCG CPD 48hr Rep1 Rotational Trinuc Norm")
```


```{r TCG_CPD_rotational_periodicity_XR-seq_normalized}
parseAndPlotPeriodicity(
  dataSetNames$TCG_NHF1_CPD_1h_Rep1_individual_mismatches_MNase_map_intergenic_custom_context_normalized,
  title = "TCG CPD 1hr Rep1 Rotational XR-seq Norm")
parseAndPlotPeriodicity(
  dataSetNames$TCG_NHF1_CPD_24h_Rep1_individual_mismatches_MNase_map_intergenic_custom_context_normalized,
  title = "TCG CPD 24hr Rep1 Rotational XR-seq Norm")
parseAndPlotPeriodicity(
  dataSetNames$TCG_NHF1_CPD_48h_Rep1_individual_mismatches_MNase_map_intergenic_custom_context_normalized,
  title = "TCG CPD 48hr Rep1 Rotational XR-seq Norm")
```


```{r TCG_CPD_translational_periodicity_trinuc_normalized}
parseAndPlotPeriodicity(
  dataSetNames$`TCG_NHF1_CPD_1h_Rep1_individual_mismatches_MNase_map_intergenic_trinuc_nuc-group_normalized`,
  title = "TCG CPD 1hr Rep1 Rotational Trinuc Norm")
parseAndPlotPeriodicity(
  dataSetNames$`TCG_NHF1_CPD_24h_Rep1_individual_mismatches_MNase_map_intergenic_trinuc_nuc-group_normalized`,
  title = "TCG CPD 24hr Rep1 Rotational Trinuc Norm")
parseAndPlotPeriodicity(
  dataSetNames$`TCG_NHF1_CPD_48h_Rep1_individual_mismatches_MNase_map_intergenic_trinuc_nuc-group_normalized`,
  title = "TCG CPD 48hr Rep1 Rotational Trinuc Norm")
```



```{r TCG_CPD_translational_periodicity_XR-seq_normalized}
parseAndPlotPeriodicity(
  dataSetNames$`TCG_NHF1_CPD_1h_Rep1_individual_mismatches_MNase_map_intergenic_custom_context_nuc-group_normalized`,
  title = "TCG_CPD 1hr Rep1 Rotational XR-seq Norm")
parseAndPlotPeriodicity(
  dataSetNames$`TCG_NHF1_CPD_24h_Rep1_individual_mismatches_MNase_map_intergenic_custom_context_nuc-group_normalized`,
  title = "TCG CPD 24hr Rep1 Rotational XR-seq Norm")
parseAndPlotPeriodicity(
  dataSetNames$`TCG_NHF1_CPD_48h_Rep1_individual_mismatches_MNase_map_intergenic_custom_context_nuc-group_normalized`,
  title = "TCG CPD 48hr Rep1 Rotational XR-seq Norm")
```
