---
title: "GM12878 Deamination Sequence and Position Data Generation"
author: "Ben Morledge-Hampton"
date: "5/2/2022"
output: html_document
params:
  bioinformaticsDirectory:
    label: "Bioinformatics Projects Directory"
    value: C:/Bioinformatics_Projects
    input: select
    choices: [C:/Bioinformatics_Projects, F:/Bioinformatics_Projects]
  filtering:
    label: "Filtering"
    value: NONE
    input: select
    choices: [NONE, TGG_filtered]
---


```{r setup_chunk}
library(knitr)

expansionOffset = 0
cellType = "GM12878"
cisplatinTimepoints = list(`90min` = NULL)
minReadLength = 22; maxReadLength = 30

if (interactive()) {
  bioinformaticsDirectory = choose.dir(caption = "Select Bioinformatics_Projects Directory")
  filtering = readline("Filtering identifier (Input nothing for no filtering):")
  if (filtering == '') filtering = character()
} else {
  bioinformaticsDirectory = params$bioinformaticsDirectory
  filtering = params$filtering
  if (filtering == "NONE") filtering = character()
}
if (is.na(bioinformaticsDirectory)) stop("No bioinformatics directory given.")

deaminationDataDirectory = file.path(bioinformaticsDirectory, "deamination_determination", "data", cellType)
mismatchesByReadDirectory = file.path(deaminationDataDirectory, "mismatches_by_read")
deaminationSequenceAndPositionDataDirectory = file.path(deaminationDataDirectory,"sequence_and_position_analysis")
dir.create(deaminationSequenceAndPositionDataDirectory, recursive = TRUE, showWarnings = FALSE)
```


```{r source_functions}
source(file.path(bioinformaticsDirectory, "deamination_determination", 'R',
                 "UsefulFileSystemFunctions.R"))
source(file.path(bioinformaticsDirectory, "deamination_determination", 'R',
                 "DeaminationParseAndFilter.R"))
source(file.path(bioinformaticsDirectory, "deamination_determination", 'R',
                 "DeaminationSequenceAndPositionAnalysis.R"))
```


```{r read_mismatch_data}
# Get file paths for the mismatch by read data
cisplatinMismatchData = list(rep1 = cisplatinTimepoints, rep2 = cisplatinTimepoints, all_reps = cisplatinTimepoints)
for (i in 1:length(cisplatinMismatchData)) {
  for (j in 1:length(cisplatinMismatchData[[i]])) {
    cisplatinMismatchData[[i]][[j]] = fread(generateFilePath(
      mismatchesByReadDirectory, dataTypeStrings$mismatchesByRead, ".bed",
      cellType = cellType, lesion = "cisplatin", timepoint = names(cisplatinMismatchData[[i]])[j],
      repitition = names(cisplatinMismatchData)[i], filtering = filtering
      ))
  }
}
```


```{r generate_and_write_simplified_and_filtered_mismatch_data}
# Perform general filtering on the data
cisplatinMismatchData = lapply(cisplatinMismatchData, function(x) lapply(
  x, function(y) filterResults(y, TRUE, 3, minReadLength, maxReadLength)
))

# Simplify the data
cisplatinMismatchData = lapply(cisplatinMismatchData, function(x) lapply(
  x, function(y) simplifyTable(y, includeTrinucleotideContext = TRUE)
))

# Write the simplified mismatch data
for (i in 1:length(cisplatinMismatchData)) {
  for (j in 1:length(cisplatinMismatchData[[i]])) {
    fwrite(cisplatinMismatchData[[i]][[j]], sep = '\t', na = "NA",
           file = generateFilePath(
             deaminationSequenceAndPositionDataDirectory, dataTypeStrings$simplifiedMismatches, ".tsv",
             cellType = cellType, lesion = "cisplatin", timepoint = names(cisplatinMismatchData[[i]])[j],
             repitition = names(cisplatinMismatchData)[i], filtering = filtering
           ))
  }
}
```


```{r generate_and_write_mismatch_frequency_z-scores}
# Don't forget to subset by C>T mismatches!
cisplatinMMFreqZScores = lapply(cisplatinMismatchData, function(x) lapply(
  x, function(y) {
    getMismatchFrequencyZScoreByPosAndReadLength(y[Mismatch == "C>T"], expansionOffset)
  }
))

for (i in seq_along(cisplatinMMFreqZScores)) {
  for (j in seq_along(cisplatinMMFreqZScores[[i]])) {
    fwrite(cisplatinMMFreqZScores[[i]][[j]], sep = '\t', file = generateFilePath(
      directory = deaminationSequenceAndPositionDataDirectory, dataTypeStrings$mismatchFrequencyZScores, ".tsv",
      cellType = cellType, lesion = "cisplatin", repitition = names(cisplatinMMFreqZScores)[i],
      timepoint = names(cisplatinMMFreqZScores[[i]])[j], filtering = filtering, includedMismatches = c("C>T")
    ))
  }
}
```


```{r generate_and_write_read_length_counts}
cisplatinReadLengthCounts = lapply(cisplatinMismatchData, function(x) lapply(
  x, function(y) {
    y[, .N, by = Read_Length][order(Read_Length)]
  }
))

for (i in seq_along(cisplatinReadLengthCounts)) {
  for (j in seq_along(cisplatinReadLengthCounts[[i]])) {
    fwrite(cisplatinReadLengthCounts[[i]][[j]], sep = '\t', file = generateFilePath(
      directory = deaminationSequenceAndPositionDataDirectory, dataTypeStrings$readLengthcounts, ".tsv",
      cellType = cellType, lesion = "cisplatin", repitition = names(cisplatinReadLengthCounts)[i],
      timepoint = names(cisplatinReadLengthCounts[[i]])[j], filtering = filtering
    ))
  }
}
```


```{r generate_and_write_mismatch_position_statistics_by_read_length_and_timepoint}
cisplatinGroupedStats = list(rep1 = list(), rep2 = list(), all_reps = list())
for (i in seq_along(cisplatinGroupedStats)) {
  cisplatinGroupedStats[[i]]$three_prime = getGroupedPositionStats(cisplatinMismatchData[[i]], includedTypes = c("C>T"))
  cisplatinGroupedStats[[i]]$five_prime =
    getGroupedPositionStats(cisplatinMismatchData[[i]], includedTypes = c("C>T"), posType = FIVE_PRIME)
}

for (i in seq_along(cisplatinGroupedStats)) {
  for (j in seq_along(cisplatinGroupedStats[[i]])) {
    fwrite(cisplatinGroupedStats[[i]][[j]], sep = '\t',
           file = generateFilePath(
             deaminationSequenceAndPositionDataDirectory, dataTypeStrings$mismatchPositionStats, ".tsv",
             cellType = cellType, lesion = "cisplatin", repitition = names(cisplatinGroupedStats)[i],
             strandPolarity = names(cisplatinGroupedStats[[i]])[j], filtering = filtering
           ))
  }
}
```

