---
title: "GM12878 General Read Sequence Figure Generation"
author: "Ben Morledge-Hampton"
date: "5/2/2022"
output: html_document
params:
  bioinformaticsDirectory:
    label: "Bioinformatics Projects Directory"
    value: C:/Bioinformatics_Projects
    input: select
    choices: [C:/Bioinformatics_Projects, F:/Bioinformatics_Projects]
---


```{r setup_chunk}
library(knitr)

expansionOffset = 10
cellType = "GM12878"
CisplatinTimepoints = list(`90min` = NULL)
minReadLength = 22; maxReadLength = 30

opts_chunk$set(dev = "png", dpi = 600, fig.width = 7, fig.height = 5,
               fig.path = paste0(file.path("deamination_analysis_output", cellType,
                                           "general_read_analysis_figures"),
                                 .Platform$file.sep))
if (interactive()) {
  bioinformaticsDirectory = choose.dir(caption = "Select Bioinformatics_Projects Directory")
} else {
  bioinformaticsDirectory = params$bioinformaticsDirectory
}

if (is.na(bioinformaticsDirectory)) stop("No bioinformatics directory given.")

deaminationDataDirectory = file.path(bioinformaticsDirectory, "deamination_determination", "data", cellType)
generalReadSequenceDataDirectory = file.path(deaminationDataDirectory, "general_read_sequences")
```


```{r source_functions}
source(file.path(bioinformaticsDirectory, "deamination_determination", 'R',
                 "UsefulFileSystemFunctions.R"))
source(file.path(bioinformaticsDirectory, "deamination_determination", 'R',
                 "DeaminationSequenceAndPositionAnalysis.R"))
source(file.path(bioinformaticsDirectory, "deamination_determination", 'R',
                 "DeaminationAnchoredExcisionSiteAnalysis.R"))
```


```{r read_sequence_frequencies}
CisplatinTGGSeqFreq = list(rep1 = CisplatinTimepoints, rep2 = CisplatinTimepoints)
for (i in seq_along(CisplatinTGGSeqFreq)) {
  for (j in seq_along(CisplatinTGGSeqFreq[[i]])) {
    CisplatinTGGSeqFreq[[i]][[j]] = fread(generateFilePath(
      directory = generalReadSequenceDataDirectory, dataTypeStrings$sequenceFrequency, ".tsv",
      cellType = cellType, lesion = "cisplatin", repitition = names(CisplatinTGGSeqFreq)[i],
      timepoint = names(CisplatinTGGSeqFreq[[i]])[j], sequence = "TGG"
    ))
  }
}

CisplatinCGASeqFreq = list(rep1 = CisplatinTimepoints, rep2 = CisplatinTimepoints)
for (i in seq_along(CisplatinCGASeqFreq)) {
  for (j in seq_along(CisplatinCGASeqFreq[[i]])) {
    CisplatinCGASeqFreq[[i]][[j]] = fread(generateFilePath(
      directory = generalReadSequenceDataDirectory, dataTypeStrings$sequenceFrequency, ".tsv",
      cellType = cellType, lesion = "cisplatin", repitition = names(CisplatinCGASeqFreq)[i],
      timepoint = names(CisplatinCGASeqFreq[[i]])[j], sequence = "CGA"
    ))
  }
}
```


```{r cisplatin_sequence_frequencies, fig.width = 11, fig.height = 10}
plotSequenceFrequencies(CisplatinTGGSeqFreq$rep1,
                        title = "cisplatin TGG Frequencies Rep1", expansionOffset = expansionOffset,
                        showThreePrimeCutSite = TRUE, showFivePrimeCutSite = TRUE,
                        querySequences = c("TGG"))
plotSequenceFrequencies(CisplatinTGGSeqFreq$rep2,
                        title = "cisplatin TGG Frequencies Rep2", expansionOffset = expansionOffset,
                        showThreePrimeCutSite = TRUE, showFivePrimeCutSite = TRUE,
                        querySequences = c("TGG"))

plotSequenceFrequencies(CisplatinCGASeqFreq$rep1,
                        title = "cisplatin CGA Frequencies Rep1", expansionOffset = expansionOffset,
                        showThreePrimeCutSite = TRUE, showFivePrimeCutSite = TRUE,
                        querySequences = c("CGA"))
plotSequenceFrequencies(CisplatinCGASeqFreq$rep2,
                        title = "cisplatin CGA Frequencies Rep2", expansionOffset = expansionOffset,
                        showThreePrimeCutSite = TRUE, showFivePrimeCutSite = TRUE,
                        querySequences = c("CGA"))
```


```{r read_length_frequencies_plotting_function}
readAndPlotReadLengthFrequencies = function(lesion, repitition, timepoints) {
  
  readData = timepoints
  for (i in seq_along(readData)) {
    readData[[i]] = fread(generateFilePath(
      generalReadSequenceDataDirectory, dataTypeStrings$alignedReads, ".bed",
      cellType = cellType, lesion = lesion, timepoint = names(readData)[i],
      repitition = repitition, expansionNum = expansionOffset
    ))
    readData[[i]] = data.table(Read_Length = nchar(readData[[i]]$V7)-expansionOffset*2,
                               Timepoint = names(readData)[i])
    readData[[i]] = readData[[i]][Read_Length >= minReadLength-7 & Read_Length <= maxReadLength]
  }
  
  plotReadLengthFrequencies(readData,
                            title = paste(c(lesion, "Read Length Freq",
                                            tools::toTitleCase(repitition)),
                                          collapse = ' '))
  
}
```


```{r cisplatin_read_length_frequencies}
readAndPlotReadLengthFrequencies("cisplatin", "rep1", CisplatinTimepoints)
readAndPlotReadLengthFrequencies("cisplatin", "rep2", CisplatinTimepoints)
```

