---
title: "GM12878 Deamination Anchored Excision Site Figure Generation"
author: "Ben Morledge-Hampton"
date: "5/2/2022"
output: html_document
params:
  bioinformaticsDirectory:
    label: "Bioinformatics Projects Directory"
    value: C:/Bioinformatics_Projects
    input: select
    choices: [C:/Bioinformatics_Projects, F:/Bioinformatics_Projects]
  filtering:
    label: "Filtering"
    value: NONE
    input: select
    choices: [NONE, TGG_filtered]
---


```{r setup_chunk}
library(knitr)

expansionOffset = 10
cellType = "GM12878"
CisplatinTimepoints = list(`90min` = NULL)
minReadLength = 22; maxReadLength = 30

if (interactive()) {
  bioinformaticsDirectory = choose.dir(caption = "Select Bioinformatics_Projects Directory")
  filtering = readline("Filtering identifier (Input nothing for no filtering):")
  if (filtering == '') filtering = character()
} else {
  bioinformaticsDirectory = params$bioinformaticsDirectory
  filtering = params$filtering
  if (filtering == "NONE") filtering = character()
}
if (length(filtering) > 0) {
  titleCaseFiltering = tools::toTitleCase(gsub('_', ' ', filtering))
} else titleCaseFiltering = character()

opts_chunk$set(dev = "png", dpi = 600, fig.width = 7, fig.height = 5, 
               fig.path = paste0(file.path("deamination_analysis_output", cellType,
                                           paste(c(filtering,"deamination_anchored_excision_site_figures"), collapse = '_')),
                                 .Platform$file.sep))

deaminationDataDirectory = file.path(bioinformaticsDirectory, "deamination_determination", "data", cellType)
deaminationExcisionSiteDataDirectory = file.path(deaminationDataDirectory, "excision_site_analysis")
```


```{r source_functions}
source(file.path(bioinformaticsDirectory, "deamination_determination", 'R',
                 "UsefulFileSystemFunctions.R"))
source(file.path(bioinformaticsDirectory, "deamination_determination", 'R',
                 "DeaminationAnchoredExcisionSiteAnalysis.R"))
```


```{r read_nucleotide_frequency_data}
threePrimeMismatchCisplatinNucFreq = list(rep1 = NULL, rep2 = NULL)
for (i in seq_along(threePrimeMismatchCisplatinNucFreq)) {
  threePrimeMismatchCisplatinNucFreq[[i]] = fread(generateFilePath(
    directory = deaminationExcisionSiteDataDirectory, dataTypeStrings$nucleotideFrequencyData, ".tsv",
    cellType = cellType, lesion = "cisplatin", repitition = names(threePrimeMismatchCisplatinNucFreq)[i],
    strandPolarity = "three_prime", anchored = TRUE, filtering = filtering
  ))
}

fivePrimeMismatchCisplatinNucFreq = list(rep1 = NULL, rep2 = NULL)
for (i in seq_along(fivePrimeMismatchCisplatinNucFreq)) {
  fivePrimeMismatchCisplatinNucFreq[[i]] = fread(generateFilePath(
    directory = deaminationExcisionSiteDataDirectory, dataTypeStrings$nucleotideFrequencyData, ".tsv",
    cellType = cellType, lesion = "cisplatin", repitition = names(fivePrimeMismatchCisplatinNucFreq)[i],
    strandPolarity = "five_prime", anchored = TRUE, filtering = filtering
  ))
}
```


```{r cisplatin_mismatch_anchored_nucleotide_frequencies, fig.width = 11, fig.height = 9}
plotNucFreqVsReadLengthBarPlot(threePrimeMismatchCisplatinNucFreq$rep1, 
                               title = paste(c("cisplatin", titleCaseFiltering, "3' Anchored Nuc Freq Rep1"), collapse = ' '),
                               secondaryYAxisLabel = "5' Cut Site Distance",
                               posType = THREE_PRIME, showFivePrimeCutSite = TRUE, expansionOffset = expansionOffset)
plotNucFreqVsReadLengthBarPlot(threePrimeMismatchCisplatinNucFreq$rep2, 
                               title = paste(c("cisplatin", titleCaseFiltering, "3' Anchored Nuc Freq Rep2"), collapse = ' '),
                               secondaryYAxisLabel = "5' Cut Site Distance",
                               posType = THREE_PRIME, showFivePrimeCutSite = TRUE, expansionOffset = expansionOffset)

plotNucFreqVsReadLengthBarPlot(fivePrimeMismatchCisplatinNucFreq$rep1, 
                               title = paste(c("cisplatin", titleCaseFiltering, "5' Anchored Nuc Freq Rep1"), collapse = ' '),
                               yAxisLabel = "Purine Frequency", secondaryYAxisLabel = "3' Cut Site Distance",
                               posType = FIVE_PRIME, showThreePrimeCutSite = TRUE, expansionOffset = expansionOffset)
plotNucFreqVsReadLengthBarPlot(fivePrimeMismatchCisplatinNucFreq$rep2, 
                               title = paste(c("cisplatin", titleCaseFiltering, "5' Anchored Nuc Freq Rep2"), collapse = ' '),
                               yAxisLabel = "Purine Frequency", secondaryYAxisLabel = "3' Cut Site Distance",
                               posType = FIVE_PRIME, showThreePrimeCutSite = TRUE, expansionOffset = expansionOffset)
```


```{r cisplatin_mismatch_anchored_purine_frequencies, fig.width = 11, fig.height = 9}
plotNucFreqVsReadLengthBarPlot(threePrimeMismatchCisplatinNucFreq$rep1, 
                               title = paste(c("cisplatin", titleCaseFiltering, "3' Anchored Purine Freq Rep1"), collapse = ' '),
                               yAxisLabel = "Purine Frequency", secondaryYAxisLabel = "5' Cut Site Distance",
                               combineNucleotides = c("AG"), combinedNames = c("Purine"),
                               posType = THREE_PRIME, showFivePrimeCutSite = TRUE, expansionOffset = expansionOffset)
plotNucFreqVsReadLengthBarPlot(threePrimeMismatchCisplatinNucFreq$rep2, 
                               title = paste(c("cisplatin", titleCaseFiltering, "3' Anchored Purine Freq Rep2"), collapse = ' '),
                               yAxisLabel = "Purine Frequency", secondaryYAxisLabel = "5' Cut Site Distance",
                               combineNucleotides = c("AG"), combinedNames = c("Purine"),
                               posType = THREE_PRIME, showFivePrimeCutSite = TRUE, expansionOffset = expansionOffset)

plotNucFreqVsReadLengthBarPlot(fivePrimeMismatchCisplatinNucFreq$rep1, 
                               title = paste(c("cisplatin", titleCaseFiltering, "5' Anchored Purine Freq Rep1"), collapse = ' '),
                               yAxisLabel = "Purine Frequency", secondaryYAxisLabel = "3' Cut Site Distance",
                               combineNucleotides = c("AG"), combinedNames = c("Purine"),
                               posType = FIVE_PRIME, showThreePrimeCutSite = TRUE, expansionOffset = expansionOffset)
plotNucFreqVsReadLengthBarPlot(fivePrimeMismatchCisplatinNucFreq$rep2, 
                               title = paste(c("cisplatin", titleCaseFiltering, "5' Anchored Purine Freq Rep2"), collapse = ' '),
                               yAxisLabel = "Purine Frequency", secondaryYAxisLabel = "3' Cut Site Distance",
                               combineNucleotides = c("AG"), combinedNames = c("Purine"),
                               posType = FIVE_PRIME, showThreePrimeCutSite = TRUE, expansionOffset = expansionOffset)
```


```{r read_sequence_enrichment_data}
threePrimeMMAnchoredCisplatinEnrichment = list(rep1 = CisplatinTimepoints,
                                               rep2 = CisplatinTimepoints)
for (i in seq_along(threePrimeMMAnchoredCisplatinEnrichment)) {
  for (j in seq_along(threePrimeMMAnchoredCisplatinEnrichment[[i]])) {
    threePrimeMMAnchoredCisplatinEnrichment[[i]][[j]] = fread(generateFilePath(
      directory = deaminationExcisionSiteDataDirectory, dataTypeStrings$sequenceEnrichment, ".tsv",
      cellType = cellType, lesion = "cisplatin", repitition = names(threePrimeMMAnchoredCisplatinEnrichment)[i],
      timepoint = names(threePrimeMMAnchoredCisplatinEnrichment[[i]])[j], strandPolarity = "three_prime",
      anchored = TRUE, sequence = "YR", filtering = filtering
    ))
  }
}

fivePrimeMMAnchoredCisplatinEnrichment = list(rep1 = CisplatinTimepoints,
                                              rep2 = CisplatinTimepoints)
for (i in seq_along(fivePrimeMMAnchoredCisplatinEnrichment)) {
  for (j in seq_along(fivePrimeMMAnchoredCisplatinEnrichment[[i]])) {
    fivePrimeMMAnchoredCisplatinEnrichment[[i]][[j]] = fread(generateFilePath(
      directory = deaminationExcisionSiteDataDirectory, dataTypeStrings$sequenceEnrichment, ".tsv",
      cellType = cellType, lesion = "cisplatin", repitition = names(fivePrimeMMAnchoredCisplatinEnrichment)[i],
      timepoint = names(fivePrimeMMAnchoredCisplatinEnrichment[[i]])[j], strandPolarity = "five_prime",
      anchored = TRUE, sequence = "TGG", filtering = filtering
    ))
  }
}
```


```{r cisplatin_sequence_enrichment, fig.width = 11, fig.height = 9}
plotSequenceEnrichment(threePrimeMMAnchoredCisplatinEnrichment$rep1,
                       title = paste(c("cisplatin", titleCaseFiltering, "3' Anchored YR Enrichment Rep1"), collapse = ' '),
                       secondaryYAxisLabel = "5' Cut Site Distance", showFivePrimeCutSite = TRUE,
                       expansionOffset = expansionOffset, querySequences = c("CG","CA","TG","TA"))
plotSequenceEnrichment(threePrimeMMAnchoredCisplatinEnrichment$rep2,
                       title = paste(c("cisplatin", titleCaseFiltering, "3' Anchored YR Enrichment Rep2"), collapse = ' '),
                       secondaryYAxisLabel = "5' Cut Site Distance", showFivePrimeCutSite = TRUE,
                       expansionOffset = expansionOffset, querySequences = c("CG","CA","TG","TA"))

plotSequenceEnrichment(fivePrimeMMAnchoredCisplatinEnrichment$rep1,
                       title = paste(c("cisplatin", titleCaseFiltering, "5' Anchored TGG Enrichment Rep1"), collapse = ' '),
                       secondaryYAxisLabel = "3' Cut Site Distance", showThreePrimeCutSite = TRUE,
                       expansionOffset = expansionOffset, posType = FIVE_PRIME, querySequences = c("TGG"))
plotSequenceEnrichment(fivePrimeMMAnchoredCisplatinEnrichment$rep2,
                       title = paste(c("cisplatin", titleCaseFiltering, "5' Anchored TGG Enrichment Rep2"), collapse = ' '),
                       secondaryYAxisLabel = "3' Cut Site Distance", showThreePrimeCutSite = TRUE,
                       expansionOffset = expansionOffset, posType = FIVE_PRIME, querySequences = c("TGG"))
```


```{r read_sequence_frequency_data}
threePrimeMMAnchoredCisplatinSeqFreq = list(rep1 = CisplatinTimepoints,
                                            rep2 = CisplatinTimepoints)
for (i in seq_along(threePrimeMMAnchoredCisplatinSeqFreq)) {
  for (j in seq_along(threePrimeMMAnchoredCisplatinSeqFreq[[i]])) {
    threePrimeMMAnchoredCisplatinSeqFreq[[i]][[j]] = fread(generateFilePath(
      directory = deaminationExcisionSiteDataDirectory, dataTypeStrings$sequenceFrequency, ".tsv",
      cellType = cellType, lesion = "cisplatin", repitition = names(threePrimeMMAnchoredCisplatinSeqFreq)[i],
      timepoint = names(threePrimeMMAnchoredCisplatinSeqFreq[[i]])[j], strandPolarity = "three_prime",
      anchored = TRUE, sequence = "YR", filtering = filtering
    ))
  }
}

fivePrimeMMAnchoredCisplatinSeqFreq = list(rep1 = CisplatinTimepoints,
                                           rep2 = CisplatinTimepoints)
for (i in seq_along(fivePrimeMMAnchoredCisplatinSeqFreq)) {
  for (j in seq_along(fivePrimeMMAnchoredCisplatinSeqFreq[[i]])) {
    fivePrimeMMAnchoredCisplatinSeqFreq[[i]][[j]] = fread(generateFilePath(
      directory = deaminationExcisionSiteDataDirectory, dataTypeStrings$sequenceFrequency, ".tsv",
      cellType = cellType, lesion = "cisplatin", repitition = names(fivePrimeMMAnchoredCisplatinSeqFreq)[i],
      timepoint = names(fivePrimeMMAnchoredCisplatinSeqFreq[[i]])[j], strandPolarity = "five_prime",
      anchored = TRUE, sequence = "TGG", filtering = filtering
    ))
  }
}
```


```{r cisplatin_sequence_frequencies, fig.width = 11, fig.height = 9}
plotSequenceFrequencies(threePrimeMMAnchoredCisplatinSeqFreq$rep1,
                        title = paste(c("cisplatin", titleCaseFiltering, "3' Anchored YR Freq Rep1"), collapse = ' '),
                        secondaryYAxisLabel = "5' Cut Site Distance", showFivePrimeCutSite = TRUE,
                        expansionOffset = expansionOffset, querySequences = c("CG","CA","TG","TA"))
plotSequenceFrequencies(threePrimeMMAnchoredCisplatinSeqFreq$rep2,
                        title = paste(c("cisplatin", titleCaseFiltering, "3' Anchored YR Freq Rep2"), collapse = ' '),
                        secondaryYAxisLabel = "5' Cut Site Distance", showFivePrimeCutSite = TRUE,
                        expansionOffset = expansionOffset, querySequences = c("CG","CA","TG","TA"))

plotSequenceFrequencies(fivePrimeMMAnchoredCisplatinSeqFreq$rep1,
                        title = paste(c("cisplatin", titleCaseFiltering, "5' Anchored TGG Freq Rep1"), collapse = ' '),
                        secondaryYAxisLabel = "3' Cut Site Distance", showThreePrimeCutSite = TRUE,
                        expansionOffset = expansionOffset, posType = FIVE_PRIME, querySequences = c("TGG"))
plotSequenceFrequencies(fivePrimeMMAnchoredCisplatinSeqFreq$rep2,
                        title = paste(c("cisplatin", titleCaseFiltering, "5' Anchored TGG Freq Rep2"), collapse = ' '),
                        secondaryYAxisLabel = "3' Cut Site Distance", showThreePrimeCutSite = TRUE,
                        expansionOffset = expansionOffset, posType = FIVE_PRIME, querySequences = c("TGG"))
```

