---
title: "NHF1 Tandem Deamination Figure Generation"
author: "Ben Morledge-Hampton"
date: "5/2/2022"
output: html_document
params:
  bioinformaticsDirectory:
    label: "Bioinformatics Projects Directory"
    value: C:/Bioinformatics_Projects
    input: select
    choices: [C:/Bioinformatics_Projects, F:/Bioinformatics_Projects]
  filtering:
    label: "Filtering"
    value: NONE
    input: select
    choices: [NONE, TGG_filtered]
  mismatchType:
    label: "Mismatch Type"
    value: CC>TT
    input: select
    choices: [CC>TT, GG>AA]
---


```{r setup_chunk}
library(knitr)
library(stringr)

expansionOffset = 10
cellType = "GM12878"
cisplatinTimepoints = list(`90min` = NULL)
minReadLength = 22; maxReadLength = 30

if (interactive()) {
  bioinformaticsDirectory = choose.dir(caption = "Select Bioinformatics_Projects Directory")
  filtering = readline("Filtering identifier (Input nothing for no filtering):")
  if (filtering == '') filtering = character()
  mismatchType = readline("Tandem mismatch type:")
} else {
  bioinformaticsDirectory = params$bioinformaticsDirectory
  filtering = params$filtering
  if (filtering == "NONE") filtering = character()
  mismatchType = params$mismatchType
}
if (length(filtering) > 0) {
  titleCaseFiltering = tools::toTitleCase(gsub('_', ' ', filtering))
} else titleCaseFiltering = character()
titleCaseMismatchType = tools::toTitleCase(gsub('>', " To ", mismatchType))

opts_chunk$set(dev = "png", dpi = 600, fig.width = 7, fig.height = 5, 
               fig.path = paste0(file.path("deamination_analysis_output",cellType,
                                           paste(c(filtering,
                                                   gsub('>', "_to_", mismatchType),
                                                   "tandem_deamination_figures"), collapse = '_')),
                                 .Platform$file.sep))

deaminationDataDirectory = file.path(bioinformaticsDirectory, "deamination_determination", "data", cellType)
deaminationSequenceAndPositionDataDirectory = file.path(deaminationDataDirectory,"sequence_and_position_analysis")
deaminationExcisionSiteDataDirectory = file.path(deaminationDataDirectory, "excision_site_analysis")
```


```{r source_functions}
source(file.path(bioinformaticsDirectory, "deamination_determination", 'R',
                 "UsefulFileSystemFunctions.R"))
source(file.path(bioinformaticsDirectory, "deamination_determination", 'R',
                 "DeaminationSequenceAndPositionAnalysis.R"))
source(file.path(bioinformaticsDirectory, "deamination_determination", 'R',
                 "DeaminationAnchoredExcisionSiteAnalysis.R"))
```


```{r read_simplified_mismatch_data}
# Get file paths for the mismatch by read data
cisplatinMismatchData = list(rep1 = cisplatinTimepoints,
                             rep2 = cisplatinTimepoints)
for (i in seq_along(cisplatinMismatchData)) {
  for (j in seq_along(cisplatinMismatchData[[i]])) {
    cisplatinMismatchData[[i]][[j]] = fread(generateFilePath(
      deaminationSequenceAndPositionDataDirectory, dataTypeStrings$simplifiedMismatches, ".tsv",
      cellType = cellType, lesion = "cisplatin", timepoint = names(cisplatinMismatchData[[i]])[j],
      repitition = names(cisplatinMismatchData)[i], filtering = filtering, includedMismatches = mismatchType
    ))
  }
}
```


```{r cisplatin_mismatch_pos_frequency}
for (i in 1:length(cisplatinMismatchData)) {
  for (j in 1:length(cisplatinMismatchData[[i]])) {
    plotMismatchPositionFrequencies(cisplatinMismatchData[[i]][[j]],
                                    title = paste(c("cisplatin", titleCaseFiltering, titleCaseMismatchType,
                                                    names(cisplatinMismatchData)[i], 
                                                    names(cisplatinMismatchData[[i]])[j], "Mismatch Pos"),
                                                  collapse = ' '))
  }
}
```


```{r read_mismatch_frequency_z-score_tables}
cisplatinMMFreqZScores = list(rep1 = cisplatinTimepoints, rep2 = cisplatinTimepoints)
for (i in seq_along(cisplatinMMFreqZScores)) {
  for (j in seq_along(cisplatinMMFreqZScores[[i]])) {
    cisplatinMMFreqZScores[[i]][[j]] = fread(generateFilePath(
      directory = deaminationSequenceAndPositionDataDirectory, dataTypeStrings$mismatchFrequencyZScores, ".tsv",
      cellType = cellType, lesion = "cisplatin", repitition = names(cisplatinMMFreqZScores)[i],
      timepoint = names(cisplatinMMFreqZScores[[i]])[j], filtering = filtering, includedMismatches = mismatchType
    ))
  }
}
```


```{r cisplatin_mismatch_position_frequencies_by_read_length, fig.width = 9, fig.height = 5}
plotPositionAcrossTimepointAndReadLength(cisplatinMismatchData$rep1,
                                         title = paste(c("cisplatin", titleCaseFiltering, titleCaseMismatchType,
                                                         "Mismatch Pos Freq Rep1"),
                                                       collapse = ' '),
                                         zScoreTables = cisplatinMMFreqZScores$rep1)
plotPositionAcrossTimepointAndReadLength(cisplatinMismatchData$rep2,
                                         title = paste(c("cisplatin", titleCaseFiltering, titleCaseMismatchType,
                                                         "Mismatch Pos Freq Rep2"),
                                                       collapse = ' '),
                                         zScoreTables = cisplatinMMFreqZScores$rep2)
plotPositionAcrossTimepointAndReadLength(cisplatinMismatchData$rep1, posType = FIVE_PRIME,
                                         title = paste(c("cisplatin", titleCaseFiltering, titleCaseMismatchType,
                                                         "Mismatch Pos Freq Rep1"),
                                                       collapse = ' '),
                                         zScoreTables = cisplatinMMFreqZScores$rep1)
plotPositionAcrossTimepointAndReadLength(cisplatinMismatchData$rep2, posType = FIVE_PRIME,
                                         title = paste(c("cisplatin", titleCaseFiltering, titleCaseMismatchType,
                                                         "Mismatch Pos Freq Rep2"),
                                                       collapse = ' '),
                                         zScoreTables = cisplatinMMFreqZScores$rep2)
```


```{r cisplatin_read_length_distributions}
plotReadLengthFrequencies(cisplatinMismatchData$rep1,
                          title = paste(c("cisplatin", titleCaseFiltering, titleCaseMismatchType,
                                          "Read Length Freq Rep1"), collapse = ' '))
plotReadLengthFrequencies(cisplatinMismatchData$rep2,
                          title = paste(c("cisplatin", titleCaseFiltering, titleCaseMismatchType,
                                          "Read Length Freq Rep2"), collapse = ' '))
```


```{r read_mismatch_position_statistics}
cisplatinGroupedStats = list(rep1 = list(three_prime = NULL, five_prime = NULL),
                             rep2 = list(three_prime = NULL, five_prime = NULL))
for (i in seq_along(cisplatinGroupedStats)) {
  for (j in seq_along(cisplatinGroupedStats[[i]])) {
    cisplatinGroupedStats[[i]][[j]] = fread(generateFilePath(
      deaminationSequenceAndPositionDataDirectory, dataTypeStrings$mismatchPositionStats, ".tsv",
      cellType = cellType, lesion = "cisplatin", repitition = names(cisplatinGroupedStats)[i],
      strandPolarity = names(cisplatinGroupedStats[[i]])[j], filtering = filtering,
      includedMismatches = mismatchType
    ))
  }
}
```


```{r cisplatin_position_differences_across_read_lengths, fig.width = 9, fig.height = 5}
plotGroupedPositionStats(cisplatinGroupedStats$rep1$three_prime, cisplatinGroupedStats$rep1$five_prime, POS_DIFF,
                         title = paste(c("cisplatin", titleCaseFiltering, titleCaseMismatchType,
                                         "Mismatch Pos Diff Rep1"), collapse = ' '),
                         xAxisBreaks = c(minReadLength:maxReadLength))
plotGroupedPositionStats(cisplatinGroupedStats$rep2$three_prime, cisplatinGroupedStats$rep2$five_prime, POS_DIFF,
                         title = paste(c("cisplatin", titleCaseFiltering, titleCaseMismatchType,
                                         "Mismatch Pos Diff Rep2"), collapse = ' '),
                         xAxisBreaks = c(minReadLength:maxReadLength))
```

EXCISION SITE FIGURE GENERATION STARTS HERE

```{r read_nucleotide_frequency_data}
threePrimeMismatchCisplatinNucFreq = list(rep1 = NULL, rep2 = NULL)
for (i in seq_along(threePrimeMismatchCisplatinNucFreq)) {
  threePrimeMismatchCisplatinNucFreq[[i]] = fread(generateFilePath(
    directory = deaminationExcisionSiteDataDirectory, dataTypeStrings$nucleotideFrequencyData, ".tsv",
    cellType = cellType, lesion = "cisplatin", repitition = names(threePrimeMismatchCisplatinNucFreq)[i],
    strandPolarity = "three_prime", anchored = TRUE, filtering = filtering, includedMismatches = mismatchType
  ))
}

fivePrimeMismatchCisplatinNucFreq = list(rep1 = NULL, rep2 = NULL)
for (i in seq_along(fivePrimeMismatchCisplatinNucFreq)) {
  fivePrimeMismatchCisplatinNucFreq[[i]] = fread(generateFilePath(
    directory = deaminationExcisionSiteDataDirectory, dataTypeStrings$nucleotideFrequencyData, ".tsv",
    cellType = cellType, lesion = "cisplatin", repitition = names(fivePrimeMismatchCisplatinNucFreq)[i],
    strandPolarity = "five_prime", anchored = TRUE, filtering = filtering, includedMismatches = mismatchType
  ))
}
```


```{r cisplatin_mismatch_anchored_nucleotide_frequencies, fig.width = 11, fig.height = 9}
plotNucFreqVsReadLengthBarPlot(threePrimeMismatchCisplatinNucFreq$rep1, 
                               title = paste(c("cisplatin", titleCaseFiltering, titleCaseMismatchType,
                                               "3' Anchored Nuc Freq Rep1"), collapse = ' '),
                               secondaryYAxisLabel = "5' Cut Site Distance",
                               posType = THREE_PRIME, showFivePrimeCutSite = TRUE, expansionOffset = expansionOffset)
plotNucFreqVsReadLengthBarPlot(threePrimeMismatchCisplatinNucFreq$rep2, 
                               title = paste(c("cisplatin", titleCaseFiltering, titleCaseMismatchType,
                                               "3' Anchored Nuc Freq Rep2"), collapse = ' '),
                               secondaryYAxisLabel = "5' Cut Site Distance",
                               posType = THREE_PRIME, showFivePrimeCutSite = TRUE, expansionOffset = expansionOffset)

plotNucFreqVsReadLengthBarPlot(fivePrimeMismatchCisplatinNucFreq$rep1, 
                               title = paste(c("cisplatin", titleCaseFiltering, titleCaseMismatchType,
                                               "5' Anchored Nuc Freq Rep1"), collapse = ' '),
                               yAxisLabel = "Purine Frequency", secondaryYAxisLabel = "3' Cut Site Distance",
                               posType = FIVE_PRIME, showThreePrimeCutSite = TRUE, expansionOffset = expansionOffset)
plotNucFreqVsReadLengthBarPlot(fivePrimeMismatchCisplatinNucFreq$rep2, 
                               title = paste(c("cisplatin", titleCaseFiltering, titleCaseMismatchType,
                                               "5' Anchored Nuc Freq Rep2"), collapse = ' '),
                               yAxisLabel = "Purine Frequency", secondaryYAxisLabel = "3' Cut Site Distance",
                               posType = FIVE_PRIME, showThreePrimeCutSite = TRUE, expansionOffset = expansionOffset)
```


```{r cisplatin_mismatch_anchored_purine_frequencies, fig.width = 11, fig.height = 9}
plotNucFreqVsReadLengthBarPlot(threePrimeMismatchCisplatinNucFreq$rep1, 
                               title = paste(c("cisplatin", titleCaseFiltering, titleCaseMismatchType,
                                               "3' Anchored Purine Freq Rep1"), collapse = ' '),
                               yAxisLabel = "Purine Frequency", secondaryYAxisLabel = "5' Cut Site Distance",
                               combineNucleotides = c("AG"), combinedNames = c("Purine"),
                               posType = THREE_PRIME, showFivePrimeCutSite = TRUE, expansionOffset = expansionOffset)
plotNucFreqVsReadLengthBarPlot(threePrimeMismatchCisplatinNucFreq$rep2, 
                               title = paste(c("cisplatin", titleCaseFiltering, titleCaseMismatchType,
                                               "3' Anchored Purine Freq Rep2"), collapse = ' '),
                               yAxisLabel = "Purine Frequency", secondaryYAxisLabel = "5' Cut Site Distance",
                               combineNucleotides = c("AG"), combinedNames = c("Purine"),
                               posType = THREE_PRIME, showFivePrimeCutSite = TRUE, expansionOffset = expansionOffset)

plotNucFreqVsReadLengthBarPlot(fivePrimeMismatchCisplatinNucFreq$rep1, 
                               title = paste(c("cisplatin", titleCaseFiltering, titleCaseMismatchType,
                                               "5' Anchored Purine Freq Rep1"), collapse = ' '),
                               yAxisLabel = "Purine Frequency", secondaryYAxisLabel = "3' Cut Site Distance",
                               combineNucleotides = c("AG"), combinedNames = c("Purine"),
                               posType = FIVE_PRIME, showThreePrimeCutSite = TRUE, expansionOffset = expansionOffset)
plotNucFreqVsReadLengthBarPlot(fivePrimeMismatchCisplatinNucFreq$rep2, 
                               title = paste(c("cisplatin", titleCaseFiltering, titleCaseMismatchType,
                                               "5' Anchored Purine Freq Rep2"), collapse = ' '),
                               yAxisLabel = "Purine Frequency", secondaryYAxisLabel = "3' Cut Site Distance",
                               combineNucleotides = c("AG"), combinedNames = c("Purine"),
                               posType = FIVE_PRIME, showThreePrimeCutSite = TRUE, expansionOffset = expansionOffset)
```


```{r read_sequence_frequency_data}
threePrimeMMAnchoredCisplatinSeqFreq = list(rep1 = cisplatinTimepoints,
                                            rep2 = cisplatinTimepoints)
for (i in seq_along(threePrimeMMAnchoredCisplatinSeqFreq)) {
  for (j in seq_along(threePrimeMMAnchoredCisplatinSeqFreq[[i]])) {
    threePrimeMMAnchoredCisplatinSeqFreq[[i]][[j]] = fread(generateFilePath(
      directory = deaminationExcisionSiteDataDirectory, dataTypeStrings$sequenceFrequency, ".tsv",
      cellType = cellType, lesion = "cisplatin", repitition = names(threePrimeMMAnchoredCisplatinSeqFreq)[i],
      timepoint = names(threePrimeMMAnchoredCisplatinSeqFreq[[i]])[j], strandPolarity = "three_prime",
      anchored = TRUE, sequence = "YR", filtering = filtering, includedMismatches = mismatchType
    ))
  }
}

fivePrimeMMAnchoredCisplatinSeqFreq = list(rep1 = cisplatinTimepoints,
                                           rep2 = cisplatinTimepoints)
for (i in seq_along(fivePrimeMMAnchoredCisplatinSeqFreq)) {
  for (j in seq_along(fivePrimeMMAnchoredCisplatinSeqFreq[[i]])) {
    fivePrimeMMAnchoredCisplatinSeqFreq[[i]][[j]] = fread(generateFilePath(
      directory = deaminationExcisionSiteDataDirectory, dataTypeStrings$sequenceFrequency, ".tsv",
      cellType = cellType, lesion = "cisplatin", repitition = names(fivePrimeMMAnchoredCisplatinSeqFreq)[i],
      timepoint = names(fivePrimeMMAnchoredCisplatinSeqFreq[[i]])[j], strandPolarity = "five_prime",
      anchored = TRUE, sequence = "TGG", filtering = filtering, includedMismatches = mismatchType
    ))
  }
}
```


```{r cisplatin_sequence_frequencies, fig.width = 11, fig.height = 9}
plotSequenceFrequencies(threePrimeMMAnchoredCisplatinSeqFreq$rep1,
                        title = paste(c("cisplatin", titleCaseFiltering, titleCaseMismatchType,
                                        "3' Anchored YR Freq Rep1"), collapse = ' '),
                        secondaryYAxisLabel = "5' Cut Site Distance", showFivePrimeCutSite = TRUE,
                        expansionOffset = expansionOffset, querySequences = c("CG","CA","TG","TA"))
plotSequenceFrequencies(threePrimeMMAnchoredCisplatinSeqFreq$rep2,
                        title = paste(c("cisplatin", titleCaseFiltering, titleCaseMismatchType,
                                        "3' Anchored YR Freq Rep2"), collapse = ' '),
                        secondaryYAxisLabel = "5' Cut Site Distance", showFivePrimeCutSite = TRUE,
                        expansionOffset = expansionOffset, querySequences = c("CG","CA","TG","TA"))

plotSequenceFrequencies(fivePrimeMMAnchoredCisplatinSeqFreq$rep1,
                        title = paste(c("cisplatin", titleCaseFiltering, titleCaseMismatchType,
                                        "5' Anchored TGG Freq Rep1"), collapse = ' '),
                        secondaryYAxisLabel = "3' Cut Site Distance", showThreePrimeCutSite = TRUE,
                        expansionOffset = expansionOffset, posType = FIVE_PRIME, querySequences = c("TGG"))
plotSequenceFrequencies(fivePrimeMMAnchoredCisplatinSeqFreq$rep2,
                        title = paste(c("cisplatin", titleCaseFiltering, titleCaseMismatchType,
                                        "5' Anchored TGG Freq Rep2"), collapse = ' '),
                        secondaryYAxisLabel = "3' Cut Site Distance", showThreePrimeCutSite = TRUE,
                        expansionOffset = expansionOffset, posType = FIVE_PRIME, querySequences = c("TGG"))
```

