---
title: "Human Deamination Positioning Analysis"
author: "Ben Morledge-Hampton"
date: "5/2/2022"
output: html_document
params:
  bioinformaticsDirectory:
    label: "Bioinformatics Projects Directory"
    value: C:/Bioinformatics_Projects
    input: select
    choices: [C:/Bioinformatics_Projects, F:/Bioinformatics_Projects]
---


```{r setup_chunk}
library(knitr)
opts_chunk$set(dev = "png", dpi = 600, fig.width = 7, fig.height = 5, 
               fig.path = paste0(file.path("deamination_analysis_output","human_analysis_figures"),
                                 .Platform$file.sep))
if (interactive()) {
  bioinformaticsDirectory = choose.dir(caption = "Select Bioinformatics_Projects Directory")
} else {
  bioinformaticsDirectory = params$bioinformaticsDirectory
}

deaminationDataDirectory = file.path(bioinformaticsDirectory, "deamination_determination", "data", "human")
```


```{r source_functions}
source(file.path(bioinformaticsDirectory, "deamination_determination", 'R', "DeaminationAnalysis.R"))
```


```{r get_file_paths}
# Get file paths for the mismatch by read data
CPDMismatchDataFilePaths = list(rep1 = list(), rep2 = list())
CPDMismatchDataFilePaths$rep1 = list(
  hr1 = file.path(deaminationDataDirectory, "mismatches_by_read", "NHF1_CPD_1h_Rep1_mismatches_by_read.bed"),
  hr8 = file.path(deaminationDataDirectory, "mismatches_by_read", "NHF1_CPD_8h_Rep1_mismatches_by_read.bed"),
  hr24 = file.path(deaminationDataDirectory, "mismatches_by_read", "NHF1_CPD_24h_Rep1_mismatches_by_read.bed"),
  hr48 = file.path(deaminationDataDirectory, "mismatches_by_read", "NHF1_CPD_48h_Rep1_mismatches_by_read.bed")
)
CPDMismatchDataFilePaths$rep2 = list(
  hr1 = file.path(deaminationDataDirectory, "mismatches_by_read", "NHF1_CPD_1h_Rep2_mismatches_by_read.bed"),
  hr8 = file.path(deaminationDataDirectory, "mismatches_by_read", "NHF1_CPD_8h_Rep2_mismatches_by_read.bed"),
  hr24 = file.path(deaminationDataDirectory, "mismatches_by_read", "NHF1_CPD_24h_Rep2_mismatches_by_read.bed"),
  hr48 = file.path(deaminationDataDirectory, "mismatches_by_read", "NHF1_CPD_48h_Rep2_mismatches_by_read.bed")
)

sixFourMismatchDataFilePaths = list(rep1 = list(), rep2 = list())
sixFourMismatchDataFilePaths$rep1 = list(
  min5 = file.path(deaminationDataDirectory, "mismatches_by_read", "NHF1_6-4-PP_5min_Rep1_mismatches_by_read.bed"),
  min20 = file.path(deaminationDataDirectory, "mismatches_by_read", "NHF1_6-4-PP_20min_Rep1_mismatches_by_read.bed"),
  hr1 = file.path(deaminationDataDirectory, "mismatches_by_read", "NHF1_6-4-PP_1h_Rep1_mismatches_by_read.bed")
)
sixFourMismatchDataFilePaths$rep2 = list(
  min5 = file.path(deaminationDataDirectory, "mismatches_by_read", "NHF1_6-4-PP_5min_Rep2_mismatches_by_read.bed"),
  min20 = file.path(deaminationDataDirectory, "mismatches_by_read", "NHF1_6-4-PP_20min_Rep2_mismatches_by_read.bed"),
  hr1 = file.path(deaminationDataDirectory, "mismatches_by_read", "NHF1_6-4-PP_1h_Rep2_mismatches_by_read.bed")
)
```


```{r acquire_and_format_data}
CPDMismatchData = lapply(CPDMismatchDataFilePaths, function(x) lapply(x, fread))
sixFourMismatchData = lapply(sixFourMismatchDataFilePaths, function(x) lapply(x, fread))

# Perform general filtering on the data
CPDMismatchData = lapply(CPDMismatchData, function(x) lapply(
  x, function(y) filterResults(y, TRUE, 3, 23, 31)
))
sixFourMismatchData = lapply(sixFourMismatchData, function(x) lapply(
  x, function(y) filterResults(y, TRUE, 3, 23, 31)
))

# Simplify the data
CPDMismatchData = lapply(CPDMismatchData, function(x) lapply(
  x, function(y) simplifyTable(y, includeTrinucleotideContext = TRUE)
))
sixFourMismatchData = lapply(sixFourMismatchData, function(x) lapply(
  x, function(y) simplifyTable(y, includeTrinucleotideContext = TRUE)
))
```


```{r CPD_mismatch_type_frequency}
for (i in 1:length(CPDMismatchData)) {
  for (j in 1:length(CPDMismatchData[[i]])) {
    plotMismatchTypeFrequencies(CPDMismatchData[[i]][[j]],
                                title = paste("CPD", names(CPDMismatchData)[i], 
                                              names(CPDMismatchData[[i]])[j], "Mismatch Type Frequency"))
  }
}
```


```{r 6-4_mismatch_type_frequency}
for (i in 1:length(sixFourMismatchData)) {
  for (j in 1:length(sixFourMismatchData[[i]])) {
    plotMismatchTypeFrequencies(sixFourMismatchData[[i]][[j]],
                                title = paste("6-4", names(sixFourMismatchData)[i], 
                                              names(sixFourMismatchData[[i]])[j], "Mismatch Type Frequency"))
  }
}
```


```{r CPD_mismatch_pos_frequency}
for (i in 1:length(CPDMismatchData)) {
  for (j in 1:length(CPDMismatchData[[i]])) {
    plotMismatchPositionFrequencies(CPDMismatchData[[i]][[j]], includedTypes = c("C>T"),
                                    title = paste("CPD", names(CPDMismatchData)[i], 
                                                  names(CPDMismatchData[[i]])[j], "C>T Mismatch Positions"))
    plotMismatchPositionFrequencies(CPDMismatchData[[i]][[j]], omittedTypes = c("C>T"),
                                    title = paste("CPD", names(CPDMismatchData)[i], 
                                                  names(CPDMismatchData[[i]])[j], "!C>T Mismatch Positions"))
  }
}
```


```{r 6-4_mismatch_pos_frequency}
for (i in 1:length(sixFourMismatchData)) {
  for (j in 1:length(sixFourMismatchData[[i]])) {
    plotMismatchPositionFrequencies(sixFourMismatchData[[i]][[j]], includedTypes = c("C>T"),
                                    title = paste("6-4", names(sixFourMismatchData)[i], 
                                                  names(sixFourMismatchData[[i]])[j], "C>T Mismatch Positions"))
    plotMismatchPositionFrequencies(sixFourMismatchData[[i]][[j]], includedTypes = c("C>T"),
                                    title = paste("6-4", names(sixFourMismatchData)[i], 
                                                  names(sixFourMismatchData[[i]])[j], "C>T Mismatch Positions"),
                                    posType = FIVE_PRIME)
    
    plotMismatchPositionFrequencies(sixFourMismatchData[[i]][[j]], omittedTypes = c("C>T"),
                                    title = paste("6-4", names(sixFourMismatchData)[i], 
                                                  names(sixFourMismatchData[[i]])[j], "!C>T Mismatch Positions"))
  }
}
```


```{r CPD_trinucleotide_context_analysis}
for (i in 1:length(CPDMismatchData)) {
  for (j in 1:length(CPDMismatchData[[i]])) {
    plotTrinucleotideContext(CPDMismatchData[[i]][[j]], includedTypes = c("C>T"),
                             title = paste("CPD", names(CPDMismatchData)[i], names(CPDMismatchData[[i]])[j],
                                           "C>T Mismatch Trinuc Context"))
  }
}
```


```{r 6-4_trinucleotide_context_analysis}
for (i in 1:length(sixFourMismatchData)) {
  for (j in 1:length(sixFourMismatchData[[i]])) {
    plotTrinucleotideContext(sixFourMismatchData[[i]][[j]], includedTypes = c("C>T"),
                             title = paste("6-4", names(sixFourMismatchData)[i], names(sixFourMismatchData[[i]])[j],
                                           "C>T Mismatch Trinuc Context"))
  }
}
```


```{r facet_mismatch_position_frequencies, fig.width = 9, fig.height = 5}
plotPositionAcrossTimepointAndReadLength(CPDMismatchData$rep1, includedTypes = c("C>T"),
                                         title = "CPD C>T Mismatch Pos Freq Rep1")
plotPositionAcrossTimepointAndReadLength(CPDMismatchData$rep2, includedTypes = c("C>T"),
                                         title = "CPD C>T Mismatch Pos Freq Rep2")
plotPositionAcrossTimepointAndReadLength(CPDMismatchData$rep1, includedTypes = c("C>T"),
                                         title = "CPD C>T Mismatch Pos Freq Rep1", posType = FIVE_PRIME)
plotPositionAcrossTimepointAndReadLength(CPDMismatchData$rep2, includedTypes = c("C>T"),
                                         title = "CPD C>T Mismatch Pos Freq Rep2", posType = FIVE_PRIME)

plotPositionAcrossTimepointAndReadLength(sixFourMismatchData$rep1, includedTypes = c("C>T"),
                                         title = "6-4 C>T Mismatch Pos Freq Rep1")
plotPositionAcrossTimepointAndReadLength(sixFourMismatchData$rep2, includedTypes = c("C>T"),
                                         title = "6-4 C>T Mismatch Pos Freq Rep2")
plotPositionAcrossTimepointAndReadLength(sixFourMismatchData$rep1, includedTypes = c("C>T"),
                                         title = "6-4 C>T Mismatch Pos Freq Rep1", posType = FIVE_PRIME)
plotPositionAcrossTimepointAndReadLength(sixFourMismatchData$rep2, includedTypes = c("C>T"),
                                         title = "6-4 C>T Mismatch Pos Freq Rep2", posType = FIVE_PRIME)
```


```{r facet_mismatch_position_statistics}
CPDGroupedStats = list(rep1 = list(), rep2 = list())
CPDGroupedStats$rep1$three_prime = getGroupedPositionStats(CPDMismatchData$rep1, includedTypes = c("C>T"))
CPDGroupedStats$rep2$three_prime = getGroupedPositionStats(CPDMismatchData$rep2, includedTypes = c("C>T"))
CPDGroupedStats$rep1$five_prime =
  getGroupedPositionStats(CPDMismatchData$rep1, includedTypes = c("C>T"), posType = FIVE_PRIME)
CPDGroupedStats$rep2$five_prime =
  getGroupedPositionStats(CPDMismatchData$rep2, includedTypes = c("C>T"), posType = FIVE_PRIME)

sixFourGroupedStats = list(rep1 = list(), rep2 = list())
sixFourGroupedStats$rep1$three_prime = getGroupedPositionStats(sixFourMismatchData$rep1, includedTypes = c("C>T"))
sixFourGroupedStats$rep2$three_prime = getGroupedPositionStats(sixFourMismatchData$rep2, includedTypes = c("C>T"))
sixFourGroupedStats$rep1$five_prime =
  getGroupedPositionStats(sixFourMismatchData$rep1, includedTypes = c("C>T"), posType = FIVE_PRIME)
sixFourGroupedStats$rep2$five_prime =
  getGroupedPositionStats(sixFourMismatchData$rep2, includedTypes = c("C>T"), posType = FIVE_PRIME)

tableOutputDir = file.path("deamination_analysis_output","human_analysis_tables")
dir.create(tableOutputDir, recursive = TRUE)

fwrite(CPDGroupedStats$rep1$three_prime,
       file.path(tableOutputDir, "CPD_mismatch_three_prime_position_stats_rep1.tsv"),sep = '\t')
fwrite(CPDGroupedStats$rep2$three_prime,
       file.path(tableOutputDir, "CPD_mismatch_three_prime_position_stats_rep2.tsv"),sep = '\t')
fwrite(CPDGroupedStats$rep1$five_prime,
       file.path(tableOutputDir, "CPD_mismatch_five_prime_position_stats_rep1.tsv"),sep = '\t')
fwrite(CPDGroupedStats$rep2$five_prime,
       file.path(tableOutputDir, "CPD_mismatch_five_prime_position_stats_rep2.tsv"),sep = '\t')

fwrite(sixFourGroupedStats$rep1$three_prime,
       file.path(tableOutputDir, "6-4_mismatch_three_prime_position_stats_rep1.tsv"), sep = '\t')
fwrite(sixFourGroupedStats$rep2$three_prime,
       file.path(tableOutputDir, "6-4_mismatch_three_prime_position_stats_rep2.tsv"), sep = '\t')
fwrite(sixFourGroupedStats$rep1$five_prime,
       file.path(tableOutputDir, "6-4_mismatch_five_prime_position_stats_rep1.tsv"), sep = '\t')
fwrite(sixFourGroupedStats$rep2$five_prime,
       file.path(tableOutputDir, "6-4_mismatch_five_prime_position_stats_rep2.tsv"), sep = '\t')
```


```{r position_differences_across_read_lengths, fig.width = 9, fig.height = 5}
plotGroupedPositionStats(CPDGroupedStats$rep1$three_prime, CPDGroupedStats$rep1$five_prime, POS_DIFF,
                         title = "CPD C>T Mismatch Pos Diff Rep1",
                         xAxisBreaks = c(23:31))
plotGroupedPositionStats(CPDGroupedStats$rep2$three_prime, CPDGroupedStats$rep2$five_prime, POS_DIFF,
                         title = "CPD C>T Mismatch Pos Diff Rep2",
                         xAxisBreaks = c(23:31))

plotGroupedPositionStats(sixFourGroupedStats$rep1$three_prime, sixFourGroupedStats$rep1$five_prime, POS_DIFF,
                         title = "6-4 C>T Mismatch Pos Diff Rep1",
                         xAxisBreaks = c(23:31))
plotGroupedPositionStats(sixFourGroupedStats$rep2$three_prime, sixFourGroupedStats$rep2$five_prime, POS_DIFF,
                         title = "6-4 C>T Mismatch Pos Diff Rep2",
                         xAxisBreaks = c(23:31))
```


