---
title: "NHF1_FeatureRelativeDataGeneration"
author: "Ben Morledge-Hampton"
date: "2023-07-18"
output: html_document
params:
  bioinformaticsDirectory:
    label: "Bioinformatics Projects Directory"
    value: C:/Bioinformatics_Projects
    input: select
    choices: [C:/Bioinformatics_Projects, F:/Bioinformatics_Projects]
  filtering:
    label: "Filtering"
    value: NONE
    input: select
    choices: [NONE, TGG_filtered, TG_filtered]
---


```{r setup_chunk}
library(knitr)

cellType = "NHF1"
CPDTimepoints = list(`1h` = NULL, `8h` = NULL, `24h` = NULL, `48h` = NULL)
mismatchTypes = list(`C>T_CC>TT` = NULL)
features = list(`CTCF_known1_DHS` = NULL, `CTCF_known1_non-DHS` = NULL, `hg19_mnase_all` = NULL)


if (interactive()) {
  bioinformaticsDirectory = choose.dir(caption = "Select Bioinformatics_Projects Directory")
  filtering = readline("Filtering identifier (Input nothing for no filtering):")
  if (filtering == '') filtering = character()
} else {
  bioinformaticsDirectory = params$bioinformaticsDirectory
  filtering = params$filtering
  if (filtering == "NONE") filtering = character()
}
if (is.na(bioinformaticsDirectory)) stop("No bioinformatics directory given.")

deaminationDataDirectory = file.path(bioinformaticsDirectory, "deamination_determination", "data", cellType)
mismatchesByReadDirectory = file.path(deaminationDataDirectory, "mismatches_by_read")
featureRelativeDataDirectory = file.path(deaminationDataDirectory,"feature_relative_analysis")
dir.create(featureRelativeDataDirectory, showWarnings = FALSE, recursive = TRUE)
```


```{r source_functions}
source(file.path(bioinformaticsDirectory, "deamination_determination", 'R',
                 "UsefulFileSystemFunctions.R"))
source(file.path(bioinformaticsDirectory, "deamination_determination", 'R',
                 "DeaminationFeatureRelativeAnalysis.R"))
```


```{r generate_and_write_feature_relative_counts_data}
cpdFeatureRelativeData = copy(CPDTimepoints)
for (i in 1:length(cpdFeatureRelativeData)) {
  cpdFeatureRelativeData[[i]] = copy(mismatchTypes)
  for (j in 1:length(cpdFeatureRelativeData[[i]])) {
    cpdFeatureRelativeData[[i]][[j]] = copy(features)
    for (k in 1:length(cpdFeatureRelativeData[[i]][[j]])) {
      cpdFeatureRelativeData[[i]][[j]][[k]] = parseMismatchesByFeature(fread(
        generateFilePath(mismatchesByReadDirectory, dataTypeStrings$mismatchesByReadRelationFormatted, ".bed",
                         cellType = cellType, lesion = "CPD", repitition = "all_reps", filtering = filtering,
                         timepoint = names(cpdFeatureRelativeData)[i], includedMismatches = names(cpdFeatureRelativeData[[i]])[j],
                         additionalInformation = paste0(names(cpdFeatureRelativeData[[i]][[j]])[k],"_related"))
      ))
      
      fwrite(cpdFeatureRelativeData[[i]][[j]][[k]], sep = '\t', file = generateFilePath(
        featureRelativeDataDirectory, dataTypeStrings$featureRelativeData, ".tsv",
        cellType = cellType, lesion = "CPD", repitition = "all_reps", filtering = filtering,
        timepoint = names(cpdFeatureRelativeData)[i], includedMismatches = names(cpdFeatureRelativeData[[i]])[j],
        additionalInformation = paste0(names(cpdFeatureRelativeData[[i]][[j]])[k],"_related")
      ))
      
      for (bool in c(TRUE, FALSE)) {
        
        if (bool) {strandInfoText = "_strand_aligned"} else {strandInfoText = ""}
        
        fwrite(getFeatureRelativeCounts(cpdFeatureRelativeData[[i]][[j]][[k]], dataType = FEATURE_RELATIVE_POSITION,
                                        strandAlign = bool),
               sep = '\t', na = "NA", file = generateFilePath(
          featureRelativeDataDirectory, dataTypeStrings$featureRelativePositionCounts, ".tsv",
          cellType = cellType, lesion = "CPD", repitition = "all_reps", filtering = filtering,
          timepoint = names(cpdFeatureRelativeData)[i], includedMismatches = names(cpdFeatureRelativeData[[i]])[j],
          additionalInformation = paste0(names(cpdFeatureRelativeData[[i]][[j]])[k],"_related",strandInfoText)
        ))
        
        fwrite(getFeatureRelativeCounts(cpdFeatureRelativeData[[i]][[j]][[k]], dataType = FEATURE_RELATIVE_THREE_PRIME_CUT_SITE,
                                        strandAlign = bool),
               sep = '\t', na = "NA", file = generateFilePath(
          featureRelativeDataDirectory, dataTypeStrings$featureRelativeCutSiteCounts, ".tsv", strandPolarity = THREE_PRIME,
          cellType = cellType, lesion = "CPD", repitition = "all_reps", filtering = filtering,
          timepoint = names(cpdFeatureRelativeData)[i], includedMismatches = names(cpdFeatureRelativeData[[i]])[j],
          additionalInformation = paste0(names(cpdFeatureRelativeData[[i]][[j]])[k],"_related",strandInfoText)
        ))
        
        fwrite(getFeatureRelativeCounts(cpdFeatureRelativeData[[i]][[j]][[k]], dataType = FEATURE_RELATIVE_FIVE_PRIME_CUT_SITE,
                                        strandAlign = bool),
               sep = '\t', na = "NA", file = generateFilePath(
          featureRelativeDataDirectory, dataTypeStrings$featureRelativeCutSiteCounts, ".tsv", strandPolarity = FIVE_PRIME,
          cellType = cellType, lesion = "CPD", repitition = "all_reps", filtering = filtering,
          timepoint = names(cpdFeatureRelativeData)[i], includedMismatches = names(cpdFeatureRelativeData[[i]])[j],
          additionalInformation = paste0(names(cpdFeatureRelativeData[[i]][[j]])[k],"_related",strandInfoText)
        ))
        
        fwrite(getFeatureRelativeCounts(cpdFeatureRelativeData[[i]][[j]][[k]], dataType = MEAN_THREE_PRIME_CUT_SITE_DISTANCE,
                                        strandAlign = bool),
               sep = '\t', na = "NA", file = generateFilePath(
          featureRelativeDataDirectory, dataTypeStrings$featureRelativeMeanCutSiteDistance, ".tsv", strandPolarity = THREE_PRIME,
          cellType = cellType, lesion = "CPD", repitition = "all_reps", filtering = filtering,
          timepoint = names(cpdFeatureRelativeData)[i], includedMismatches = names(cpdFeatureRelativeData[[i]])[j],
          additionalInformation = paste0(names(cpdFeatureRelativeData[[i]][[j]])[k],"_related",strandInfoText)
        ))
        
        fwrite(getFeatureRelativeCounts(cpdFeatureRelativeData[[i]][[j]][[k]], dataType = MEAN_FIVE_PRIME_CUT_SITE_DISTANCE,
                                        strandAlign = bool),
               sep = '\t', na = "NA", file = generateFilePath(
          featureRelativeDataDirectory, dataTypeStrings$featureRelativeMeanCutSiteDistance, ".tsv", strandPolarity = FIVE_PRIME,
          cellType = cellType, lesion = "CPD", repitition = "all_reps", filtering = filtering,
          timepoint = names(cpdFeatureRelativeData)[i], includedMismatches = names(cpdFeatureRelativeData[[i]])[j],
          additionalInformation = paste0(names(cpdFeatureRelativeData[[i]][[j]])[k],"_related",strandInfoText)
        ))
        
      }
    }
  }
}

```
