---
title: "NHF1 Deamination Anchored Excision Site Figure Generation"
author: "Ben Morledge-Hampton"
date: "5/2/2022"
output: html_document
params:
  bioinformaticsDirectory:
    label: "Bioinformatics Projects Directory"
    value: C:/Bioinformatics_Projects
    input: select
    choices: [C:/Bioinformatics_Projects, F:/Bioinformatics_Projects]
  filtering:
    label: "Filtering"
    value: NONE
    input: select
    choices: [NONE, TGG_filtered]
---


```{r setup_chunk}
library(knitr)

expansionOffset = 10
cellType = "NHF1"
CPDTimepoints = list(`1h` = NULL, `8h` = NULL, `24h` = NULL, `48h` = NULL)
sixFourTimepoints = list(`5min` = NULL, `20min` = NULL, `1h` = NULL)
repNames = c("rep1", "rep2", "all_reps")

if (interactive()) {
  bioinformaticsDirectory = choose.dir(caption = "Select Bioinformatics_Projects Directory")
  filtering = readline("Filtering identifier (Input nothing for no filtering):")
  if (filtering == '') filtering = character()
} else {
  bioinformaticsDirectory = params$bioinformaticsDirectory
  filtering = params$filtering
  if (filtering == "NONE") filtering = character()
}
if (length(filtering) > 0) {
  titleCaseFiltering = tools::toTitleCase(gsub('_', ' ', filtering))
} else titleCaseFiltering = character()

opts_chunk$set(dev = "png", dpi = 600, fig.width = 7, fig.height = 5, 
               fig.path = paste0(file.path("deamination_analysis_output", cellType,
                                           paste(c(filtering,"deamination_anchored_excision_site_figures"), collapse = '_')),
                                 .Platform$file.sep))

deaminationDataDirectory = file.path(bioinformaticsDirectory, "deamination_determination", "data", cellType)
deaminationExcisionSiteDataDirectory = file.path(deaminationDataDirectory, "excision_site_analysis")
```


```{r source_functions}
source(file.path(bioinformaticsDirectory, "deamination_determination", 'R',
                 "UsefulFileSystemFunctions.R"))
source(file.path(bioinformaticsDirectory, "deamination_determination", 'R',
                 "DeaminationAnchoredExcisionSiteAnalysis.R"))
```


```{r read_nucleotide_frequency_data}
threePrimeMismatchCPDNucFreq = list(rep1 = NULL, rep2 = NULL, all_reps = NULL)
for (i in seq_along(threePrimeMismatchCPDNucFreq)) {
  threePrimeMismatchCPDNucFreq[[i]] = fread(generateFilePath(
    directory = deaminationExcisionSiteDataDirectory, dataTypeStrings$nucleotideFrequencyData, ".tsv",
    cellType = cellType, lesion = "CPD", repitition = names(threePrimeMismatchCPDNucFreq)[i],
    strandPolarity = "three_prime", anchored = TRUE, filtering = filtering
  ))
}

fivePrimeMismatchCPDNucFreq = list(rep1 = NULL, rep2 = NULL, all_reps = NULL)
for (i in seq_along(fivePrimeMismatchCPDNucFreq)) {
  fivePrimeMismatchCPDNucFreq[[i]] = fread(generateFilePath(
    directory = deaminationExcisionSiteDataDirectory, dataTypeStrings$nucleotideFrequencyData, ".tsv",
    cellType = cellType, lesion = "CPD", repitition = names(fivePrimeMismatchCPDNucFreq)[i],
    strandPolarity = "five_prime", anchored = TRUE, filtering = filtering
  ))
}


threePrimeMismatchSixFourNucFreq = list(rep1 = NULL, rep2 = NULL, all_reps = NULL)
for (i in seq_along(threePrimeMismatchSixFourNucFreq)) {
  threePrimeMismatchSixFourNucFreq[[i]] = fread(generateFilePath(
    directory = deaminationExcisionSiteDataDirectory, dataTypeStrings$nucleotideFrequencyData, ".tsv",
    cellType = cellType, lesion = "6-4", repitition = names(threePrimeMismatchSixFourNucFreq)[i],
    strandPolarity = "three_prime", anchored = TRUE, filtering = filtering
  ))
}

fivePrimeMismatchSixFourNucFreq = list(rep1 = NULL, rep2 = NULL, all_reps = NULL)
for (i in seq_along(fivePrimeMismatchSixFourNucFreq)) {
  fivePrimeMismatchSixFourNucFreq[[i]] = fread(generateFilePath(
    directory = deaminationExcisionSiteDataDirectory, dataTypeStrings$nucleotideFrequencyData, ".tsv",
    cellType = cellType, lesion = "6-4", repitition = names(fivePrimeMismatchSixFourNucFreq)[i],
    strandPolarity = "five_prime", anchored = TRUE, filtering = filtering
  ))
}
```


```{r CPD_mismatch_anchored_nucleotide_frequencies, fig.width = 11, fig.height = 9}
for (i in seq_along(threePrimeMismatchCPDNucFreq)) {
  plotNucFreqVsReadLengthBarPlot(threePrimeMismatchCPDNucFreq[[i]], 
                                 title = paste(c("CPD", titleCaseFiltering,
                                                 "3' Anchored Nuc Freq", repNames[i]), collapse = ' '),
                                 secondaryYAxisLabel = "5' Cut Site Distance",
                                 posType = THREE_PRIME, showFivePrimeCutSite = TRUE,
                                 expansionOffset = expansionOffset)
}

for (i in seq_along(fivePrimeMismatchCPDNucFreq)) {
  plotNucFreqVsReadLengthBarPlot(fivePrimeMismatchCPDNucFreq[[i]], 
                                 title = paste(c("CPD", titleCaseFiltering,
                                                 "5' Anchored Nuc Freq", repNames[i]), collapse = ' '),
                                 secondaryYAxisLabel = "3' Cut Site Distance",
                                 posType = FIVE_PRIME, showThreePrimeCutSite = TRUE,
                                 expansionOffset = expansionOffset)
}
```


```{r CPD_mismatch_anchored_nucleotide_frequencies_filtered, fig.width = 11, fig.height = 8}
min3PrimeCutSiteDistance = 1
max3PrimeCutSiteDistance = 12

for (i in seq_along(fivePrimeMismatchCPDNucFreq)) {
  plotNucFreqVsReadLengthBarPlot(fivePrimeMismatchCPDNucFreq[[i]], 
                                 title = paste(c("CPD", titleCaseFiltering,
                                                 "5' Anchored Nuc Freq", repNames[i]), collapse = ' '),
                                 secondaryYAxisLabel = "3' Cut Site Distance",
                                 posType = FIVE_PRIME, showThreePrimeCutSite = TRUE,
                                 expansionOffset = expansionOffset,
                                 minReadLength = min3PrimeCutSiteDistance, maxReadLength = max3PrimeCutSiteDistance)
}
```


```{r CPD_mismatch_anchored_nucleotide_frequencies_filtered_x2, fig.width = 5, fig.height = 8}
min3PrimeCutSiteDistance = 1
max3PrimeCutSiteDistance = 12

for (i in seq_along(fivePrimeMismatchCPDNucFreq)) {
  plotNucFreqVsReadLengthBarPlot(fivePrimeMismatchCPDNucFreq[[i]][Timepoint == "1h"], 
                                 title = paste(c("CPD", titleCaseFiltering,
                                                 "5' Anchored Nuc Freq", repNames[i]), collapse = ' '),
                                 secondaryYAxisLabel = "3' Cut Site Distance",
                                 posType = FIVE_PRIME, showThreePrimeCutSite = TRUE,
                                 expansionOffset = expansionOffset,
                                 minReadLength = min3PrimeCutSiteDistance, maxReadLength = max3PrimeCutSiteDistance)
}
```


```{r CPD_mismatch_anchored_purine_frequencies, fig.width = 11, fig.height = 9}
for (i in seq_along(threePrimeMismatchCPDNucFreq)) {
  plotNucFreqVsReadLengthBarPlot(threePrimeMismatchCPDNucFreq[[i]], 
                                 title = paste(c("CPD", titleCaseFiltering,
                                                 "3' Anchored Purine Freq", repNames[i]), collapse = ' '),
                                 yAxisLabel = "Purine Frequency", secondaryYAxisLabel = "5' Cut Site Distance",
                                 combineNucleotides = c("AG"), combinedNames = c("Purine"),
                                 posType = THREE_PRIME, showFivePrimeCutSite = TRUE,
                                 expansionOffset = expansionOffset)
}

for (i in seq_along(fivePrimeMismatchCPDNucFreq)) {
  plotNucFreqVsReadLengthBarPlot(fivePrimeMismatchCPDNucFreq[[i]], 
                                 title = paste(c("CPD", titleCaseFiltering,
                                                 "5' Anchored Purine Freq", repNames[i]), collapse = ' '),
                                 yAxisLabel = "Purine Frequency", secondaryYAxisLabel = "3' Cut Site Distance",
                                 combineNucleotides = c("AG"), combinedNames = c("Purine"),
                                 posType = FIVE_PRIME, showThreePrimeCutSite = TRUE,
                                 expansionOffset = expansionOffset)
}
```


```{r CPD_mismatch_anchored_purine_frequencies_filtered, fig.width = 11, fig.height = 9}
min3PrimeCutSiteDistance = 1
max3PrimeCutSiteDistance = 12

for (i in seq_along(fivePrimeMismatchCPDNucFreq)) {
  plotNucFreqVsReadLengthBarPlot(fivePrimeMismatchCPDNucFreq[[i]], 
                                 title = paste(c("CPD", titleCaseFiltering,
                                                 "5' Anchored Purine Freq", repNames[i]), collapse = ' '),
                                 yAxisLabel = "Purine Frequency", secondaryYAxisLabel = "3' Cut Site Distance",
                                 combineNucleotides = c("AG"), combinedNames = c("Purine"),
                                 posType = FIVE_PRIME, showThreePrimeCutSite = TRUE,
                                 expansionOffset = expansionOffset,
                                 minReadLength = min3PrimeCutSiteDistance, maxReadLength = max3PrimeCutSiteDistance)
}
```


```{r CPD_mismatch_anchored_purine_frequencies_filtered_x2, fig.width = 5, fig.height = 9}
min3PrimeCutSiteDistance = 1
max3PrimeCutSiteDistance = 12

for (i in seq_along(fivePrimeMismatchCPDNucFreq)) {
  plotNucFreqVsReadLengthBarPlot(fivePrimeMismatchCPDNucFreq[[i]][Timepoint == "1h"], 
                                 title = paste(c("CPD", titleCaseFiltering,
                                                 "5' Anchored Purine Freq", repNames[i]), collapse = ' '),
                                 yAxisLabel = "Purine Frequency", secondaryYAxisLabel = "3' Cut Site Distance",
                                 combineNucleotides = c("AG"), combinedNames = c("Purine"),
                                 posType = FIVE_PRIME, showThreePrimeCutSite = TRUE,
                                 expansionOffset = expansionOffset,
                                 minReadLength = min3PrimeCutSiteDistance, maxReadLength = max3PrimeCutSiteDistance)
}
```


```{r 6-4_mismatch_anchored_nucleotide_frequencies, fig.width = 11, fig.height = 9}
for (i in seq_along(threePrimeMismatchSixFourNucFreq)) {
  plotNucFreqVsReadLengthBarPlot(threePrimeMismatchSixFourNucFreq[[i]], 
                                 title = paste(c("6-4", titleCaseFiltering,
                                                 "3' Anchored Nuc Freq", repNames[i]), collapse = ' '),
                                 secondaryYAxisLabel = "5' Cut Site Distance",
                                 posType = THREE_PRIME, showFivePrimeCutSite = TRUE,
                                 expansionOffset = expansionOffset)
}

for (i in seq_along(fivePrimeMismatchSixFourNucFreq)) {
  plotNucFreqVsReadLengthBarPlot(fivePrimeMismatchSixFourNucFreq[[i]], 
                                 title = paste(c("6-4", titleCaseFiltering,
                                                 "5' Anchored Nuc Freq", repNames[i]), collapse = ' '),
                                 secondaryYAxisLabel = "3' Cut Site Distance",
                                 posType = FIVE_PRIME, showThreePrimeCutSite = TRUE,
                                 expansionOffset = expansionOffset)
}
```


```{r 6-4_mismatch_anchored_purine_frequencies, fig.width = 11, fig.height = 9}
for (i in seq_along(threePrimeMismatchSixFourNucFreq)) {
  plotNucFreqVsReadLengthBarPlot(threePrimeMismatchSixFourNucFreq[[i]], 
                                 title = paste(c("6-4", titleCaseFiltering,
                                                 "3' Anchored Purine Freq", repNames[i]), collapse = ' '),
                                 yAxisLabel = "Purine Frequency", secondaryYAxisLabel = "5' Cut Site Distance",
                                 combineNucleotides = c("AG"), combinedNames = c("Purine"),
                                 posType = THREE_PRIME, showFivePrimeCutSite = TRUE,
                                 expansionOffset = expansionOffset)
}

for (i in seq_along(fivePrimeMismatchSixFourNucFreq)) {
  plotNucFreqVsReadLengthBarPlot(fivePrimeMismatchSixFourNucFreq[[i]], 
                                 title = paste(c("6-4", titleCaseFiltering,
                                                 "5' Anchored Purine Freq", repNames[i]), collapse = ' '),
                                 yAxisLabel = "Purine Frequency", secondaryYAxisLabel = "3' Cut Site Distance",
                                 combineNucleotides = c("AG"), combinedNames = c("Purine"),
                                 posType = FIVE_PRIME, showThreePrimeCutSite = TRUE,
                                 expansionOffset = expansionOffset)
}
```


```{r read_sequence_enrichment_data}
threePrimeMMAnchoredCPDEnrichment = list(rep1 = CPDTimepoints, rep2 = CPDTimepoints, all_reps = CPDTimepoints)
for (i in seq_along(threePrimeMMAnchoredCPDEnrichment)) {
  for (j in seq_along(threePrimeMMAnchoredCPDEnrichment[[i]])) {
    threePrimeMMAnchoredCPDEnrichment[[i]][[j]] = fread(generateFilePath(
      directory = deaminationExcisionSiteDataDirectory, dataTypeStrings$sequenceEnrichment, ".tsv",
      cellType = cellType, lesion = "CPD", repitition = names(threePrimeMMAnchoredCPDEnrichment)[i],
      timepoint = names(threePrimeMMAnchoredCPDEnrichment[[i]])[j], strandPolarity = "three_prime",
      anchored = TRUE, sequence = "YR", filtering = filtering
    ))
  }
}

fivePrimeMMAnchoredCPDEnrichment = list(rep1 = CPDTimepoints, rep2 = CPDTimepoints, all_reps = CPDTimepoints)
for (i in seq_along(fivePrimeMMAnchoredCPDEnrichment)) {
  for (j in seq_along(fivePrimeMMAnchoredCPDEnrichment[[i]])) {
    fivePrimeMMAnchoredCPDEnrichment[[i]][[j]] = fread(generateFilePath(
      directory = deaminationExcisionSiteDataDirectory, dataTypeStrings$sequenceEnrichment, ".tsv",
      cellType = cellType, lesion = "CPD", repitition = names(fivePrimeMMAnchoredCPDEnrichment)[i],
      timepoint = names(fivePrimeMMAnchoredCPDEnrichment[[i]])[j], strandPolarity = "five_prime",
      anchored = TRUE, sequence = "TGG", filtering = filtering
    ))
  }
}


threePrimeMMAnchoredSixFourEnrichment = list(rep1 = sixFourTimepoints, rep2 = sixFourTimepoints,
                                             all_reps = sixFourTimepoints)
for (i in seq_along(threePrimeMMAnchoredSixFourEnrichment)) {
  for (j in seq_along(threePrimeMMAnchoredSixFourEnrichment[[i]])) {
    threePrimeMMAnchoredSixFourEnrichment[[i]][[j]] = fread(generateFilePath(
      directory = deaminationExcisionSiteDataDirectory, dataTypeStrings$sequenceEnrichment, ".tsv",
      cellType = cellType, lesion = "6-4", repitition = names(threePrimeMMAnchoredSixFourEnrichment)[i],
      timepoint = names(threePrimeMMAnchoredSixFourEnrichment[[i]])[j], strandPolarity = "three_prime",
      anchored = TRUE, sequence = "YR", filtering = filtering
    ))
  }
}

fivePrimeMMAnchoredSixFourEnrichment = list(rep1 = sixFourTimepoints, rep2 = sixFourTimepoints,
                                            all_reps = sixFourTimepoints)
for (i in seq_along(fivePrimeMMAnchoredSixFourEnrichment)) {
  for (j in seq_along(fivePrimeMMAnchoredSixFourEnrichment[[i]])) {
    fivePrimeMMAnchoredSixFourEnrichment[[i]][[j]] = fread(generateFilePath(
      directory = deaminationExcisionSiteDataDirectory, dataTypeStrings$sequenceEnrichment, ".tsv",
      cellType = cellType, lesion = "6-4", repitition = names(fivePrimeMMAnchoredSixFourEnrichment)[i],
      timepoint = names(fivePrimeMMAnchoredSixFourEnrichment[[i]])[j], strandPolarity = "five_prime",
      anchored = TRUE, sequence = "TGG", filtering = filtering
    ))
  }
}
```


```{r CPD_sequence_enrichment, fig.width = 11, fig.height = 9}
for (i in seq_along(threePrimeMMAnchoredCPDEnrichment)) {
  plotSequenceEnrichment(threePrimeMMAnchoredCPDEnrichment[[i]],
                         title = paste(c("CPD", titleCaseFiltering,
                                         "3' Anchored YR Enrichment", repNames[i]), collapse = ' '),
                         secondaryYAxisLabel = "5' Cut Site Distance", showFivePrimeCutSite = TRUE,
                         expansionOffset = expansionOffset, querySequences = c("CG","CA","TG","TA"))
}

for (i in seq_along(fivePrimeMMAnchoredCPDEnrichment)) {
  plotSequenceEnrichment(fivePrimeMMAnchoredCPDEnrichment[[i]],
                         title = paste(c("CPD", titleCaseFiltering,
                                         "5' Anchored TGG Enrichment", repNames[i]), collapse = ' '),
                         secondaryYAxisLabel = "3' Cut Site Distance", showThreePrimeCutSite = TRUE,
                         expansionOffset = expansionOffset, posType = FIVE_PRIME, querySequences = c("TGG"))
}
```


```{r 6-4_sequence_enrichment, fig.width = 11, fig.height = 9}
for (i in seq_along(threePrimeMMAnchoredSixFourEnrichment)) {
  plotSequenceEnrichment(threePrimeMMAnchoredSixFourEnrichment[[i]],
                         title = paste(c("6-4", titleCaseFiltering,
                                         "3' Anchored YR Enrichment", repNames[i]), collapse = ' '),
                         secondaryYAxisLabel = "5' Cut Site Distance", showFivePrimeCutSite = TRUE,
                         expansionOffset = expansionOffset, querySequences = c("CG","CA","TG","TA"))
}

for (i in seq_along(fivePrimeMMAnchoredSixFourEnrichment)) {
  plotSequenceEnrichment(fivePrimeMMAnchoredSixFourEnrichment[[i]],
                         title = paste(c("6-4", titleCaseFiltering,
                                         "5' Anchored TGG Enrichment", repNames[i]), collapse = ' '),
                         secondaryYAxisLabel = "3' Cut Site Distance", showThreePrimeCutSite = TRUE,
                         expansionOffset = expansionOffset, posType = FIVE_PRIME, querySequences = c("TGG"))
}
```


```{r enrichment_test_1}
# for (i in 1:5) {
#   testTable = data.table(Read_Length = 9,
#                          Read_Sequence = replicate(1000, paste0(sample(c('A','C','G','T'), 9, TRUE), collapse = '')))
#   testTableNucFreq = tabulateNucFreqByPosTimepointAndLength(testTable)
#   testEnrichment = getSequenceFreqByReadLengthAndPos(testTable, testTableNucFreq, c("CG","CA","TG","TA"))
#   plotSequenceEnrichment(testEnrichment, title = "CPD 3' Anchored YR Enrichment Rep1")
# }
```


```{r enrichment_test_2}
# for (i in 1:5) {
#   testTable = data.table(Read_Length = 9,
#                          Read_Sequence = replicate(1000,
#                                                    paste0(sample(c(rep('A',6),rep('C',4),rep('G',4),rep('T',6)),
#                                                                  9, TRUE), collapse = '')))
#   testTableNucFreq = tabulateNucFreqByPosTimepointAndLength(testTable)
#   testEnrichment = getSequenceFreqByReadLengthAndPos(testTable, testTableNucFreq, c("CG","CA","TG","TA"))
#   plotSequenceEnrichment(testEnrichment, title = "CPD 3' Anchored YR Enrichment Rep1")
# }
```


```{r read_sequence_frequency_data}
threePrimeMMAnchoredCPDSeqFreq = list(rep1 = CPDTimepoints, rep2 = CPDTimepoints, all_reps = CPDTimepoints)
for (i in seq_along(threePrimeMMAnchoredCPDSeqFreq)) {
  for (j in seq_along(threePrimeMMAnchoredCPDSeqFreq[[i]])) {
    threePrimeMMAnchoredCPDSeqFreq[[i]][[j]] = fread(generateFilePath(
      directory = deaminationExcisionSiteDataDirectory, dataTypeStrings$sequenceFrequency, ".tsv",
      cellType = cellType, lesion = "CPD", repitition = names(threePrimeMMAnchoredCPDSeqFreq)[i],
      timepoint = names(threePrimeMMAnchoredCPDSeqFreq[[i]])[j], strandPolarity = "three_prime",
      anchored = TRUE, sequence = "YR", filtering = filtering
    ))
  }
}

fivePrimeMMAnchoredCPDSeqFreq = list(rep1 = CPDTimepoints, rep2 = CPDTimepoints, all_reps = CPDTimepoints)
for (i in seq_along(fivePrimeMMAnchoredCPDSeqFreq)) {
  for (j in seq_along(fivePrimeMMAnchoredCPDSeqFreq[[i]])) {
    fivePrimeMMAnchoredCPDSeqFreq[[i]][[j]] = fread(generateFilePath(
      directory = deaminationExcisionSiteDataDirectory, dataTypeStrings$sequenceFrequency, ".tsv",
      cellType = cellType, lesion = "CPD", repitition = names(fivePrimeMMAnchoredCPDSeqFreq)[i],
      timepoint = names(fivePrimeMMAnchoredCPDSeqFreq[[i]])[j], strandPolarity = "five_prime",
      anchored = TRUE, sequence = "TGG", filtering = filtering
    ))
  }
}


threePrimeMMAnchoredSixFourSeqFreq = list(rep1 = sixFourTimepoints, rep2 = sixFourTimepoints,
                                          all_reps = sixFourTimepoints)
for (i in seq_along(threePrimeMMAnchoredSixFourSeqFreq)) {
  for (j in seq_along(threePrimeMMAnchoredSixFourSeqFreq[[i]])) {
    threePrimeMMAnchoredSixFourSeqFreq[[i]][[j]] = fread(generateFilePath(
      directory = deaminationExcisionSiteDataDirectory, dataTypeStrings$sequenceFrequency, ".tsv",
      cellType = cellType, lesion = "6-4", repitition = names(threePrimeMMAnchoredSixFourSeqFreq)[i],
      timepoint = names(threePrimeMMAnchoredSixFourSeqFreq[[i]])[j], strandPolarity = "three_prime",
      anchored = TRUE, sequence = "YR", filtering = filtering
    ))
  }
}

fivePrimeMMAnchoredSixFourSeqFreq = list(rep1 = sixFourTimepoints, rep2 = sixFourTimepoints,
                                         all_reps = sixFourTimepoints)
for (i in seq_along(fivePrimeMMAnchoredSixFourSeqFreq)) {
  for (j in seq_along(fivePrimeMMAnchoredSixFourSeqFreq[[i]])) {
    fivePrimeMMAnchoredSixFourSeqFreq[[i]][[j]] = fread(generateFilePath(
      directory = deaminationExcisionSiteDataDirectory, dataTypeStrings$sequenceFrequency, ".tsv",
      cellType = cellType, lesion = "6-4", repitition = names(fivePrimeMMAnchoredSixFourSeqFreq)[i],
      timepoint = names(fivePrimeMMAnchoredSixFourSeqFreq[[i]])[j], strandPolarity = "five_prime",
      anchored = TRUE, sequence = "TGG", filtering = filtering
    ))
  }
}
```


```{r CPD_sequence_frequencies, fig.width = 11, fig.height = 9}
for (i in seq_along(threePrimeMMAnchoredCPDSeqFreq)) {
  plotSequenceFrequencies(threePrimeMMAnchoredCPDSeqFreq[[i]],
                          title = paste(c("CPD", titleCaseFiltering,
                                          "3' Anchored YR Freq", repNames[i]), collapse = ' '),
                          secondaryYAxisLabel = "5' Cut Site Distance", yAxisLabel = "YR Frequency",
                          showFivePrimeCutSite = TRUE,
                          expansionOffset = expansionOffset, querySequences = c("CG","CA","TG","TA"))
}

for (i in seq_along(fivePrimeMMAnchoredCPDSeqFreq)) {
  plotSequenceFrequencies(fivePrimeMMAnchoredCPDSeqFreq[[i]],
                          title = paste(c("CPD", titleCaseFiltering,
                                          "5' Anchored TGG Freq", repNames[i]), collapse = ' '),
                          secondaryYAxisLabel = "3' Cut Site Distance", yAxisLabel = "YR Frequency",
                          showThreePrimeCutSite = TRUE,
                          expansionOffset = expansionOffset, posType = FIVE_PRIME, querySequences = c("TGG"))
}
```


```{r CPD_sequence_frequencies_filtered, fig.width = 11, fig.height = 8}
min5PrimeCutSiteDistance = 13
max5PrimeCutSiteDistance = 25
for (i in seq_along(threePrimeMMAnchoredCPDSeqFreq)) {
  plotSequenceFrequencies(threePrimeMMAnchoredCPDSeqFreq[[i]],
                          title = paste(c("CPD", titleCaseFiltering,
                                          "3' Anchored YR Freq", repNames[i]), collapse = ' '),
                          secondaryYAxisLabel = "5' Cut Site Distance", yAxisLabel = "YR Frequency",
                          showFivePrimeCutSite = TRUE,
                          expansionOffset = expansionOffset, querySequences = c("CG","CA","TG","TA"),
                          minReadLength = min5PrimeCutSiteDistance, maxReadLength = max5PrimeCutSiteDistance)
}
```


```{r CPD_sequence_frequencies_filtered_x2, fig.width = 5, fig.height = 8}
min5PrimeCutSiteDistance = 13
max5PrimeCutSiteDistance = 25
for (i in seq_along(threePrimeMMAnchoredCPDSeqFreq)) {
  plotSequenceFrequencies(threePrimeMMAnchoredCPDSeqFreq[[i]]$`1h`,
                          title = paste(c("CPD", titleCaseFiltering,
                                          "3' Anchored YR Freq", repNames[i]), collapse = ' '),
                          secondaryYAxisLabel = "5' Cut Site Distance", yAxisLabel = "YR Frequency",
                          showFivePrimeCutSite = TRUE,
                          expansionOffset = expansionOffset, querySequences = c("CG","CA","TG","TA"),
                          minReadLength = min5PrimeCutSiteDistance, maxReadLength = max5PrimeCutSiteDistance)
}
```


```{r 6-4_sequence_frequencies, fig.width = 11, fig.height = 9}
for (i in seq_along(threePrimeMMAnchoredSixFourSeqFreq)) {
  plotSequenceFrequencies(threePrimeMMAnchoredSixFourSeqFreq[[i]],
                          title = paste(c("6-4", titleCaseFiltering,
                                          "3' Anchored YR Freq", repNames[i]), collapse = ' '),
                          secondaryYAxisLabel = "5' Cut Site Distance", showFivePrimeCutSite = TRUE,
                          expansionOffset = expansionOffset, querySequences = c("CG","CA","TG","TA"))
}

for (i in seq_along(fivePrimeMMAnchoredSixFourSeqFreq)) {
  plotSequenceFrequencies(fivePrimeMMAnchoredSixFourSeqFreq[[i]],
                          title = paste(c("6-4", titleCaseFiltering,
                                          "5' Anchored TGG Freq", repNames[i]), collapse = ' '),
                          secondaryYAxisLabel = "3' Cut Site Distance", showThreePrimeCutSite = TRUE,
                          expansionOffset = expansionOffset, posType = FIVE_PRIME, querySequences = c("TGG"))
}
```


