---
title: "NHF1 Deamination Sequence and Position Figure Generation"
author: "Ben Morledge-Hampton"
date: "5/2/2022"
output: html_document
params:
  bioinformaticsDirectory:
    label: "Bioinformatics Projects Directory"
    value: C:/Bioinformatics_Projects
    input: select
    choices: [C:/Bioinformatics_Projects, F:/Bioinformatics_Projects]
---


```{r setup_chunk}
library(knitr)

cellType = "NHF1"
CPDTimepoints = list(`1h` = NULL, `8h` = NULL, `24h` = NULL, `48h` = NULL)
sixFourTimepoints = list(`5min` = NULL, `20min` = NULL, `1h` = NULL)

opts_chunk$set(dev = "png", dpi = 600, fig.width = 7, fig.height = 5, 
               fig.path = paste0(file.path("deamination_analysis_output",cellType,
                                           "deamination_sequence_and_position_figures"),
                                 .Platform$file.sep))
if (interactive()) {
  bioinformaticsDirectory = choose.dir(caption = "Select Bioinformatics_Projects Directory")
} else {
  bioinformaticsDirectory = params$bioinformaticsDirectory
}

deaminationDataDirectory = file.path(bioinformaticsDirectory, "deamination_determination", "data", cellType)
deaminationSequenceAndPositionDataDirectory = file.path(deaminationDataDirectory,"sequence_and_position_analysis")
```


```{r source_functions}
source(file.path(bioinformaticsDirectory, "deamination_determination", 'R',
                 "UsefulFileSystemFunctions.R"))
source(file.path(bioinformaticsDirectory, "deamination_determination", 'R',
                 "DeaminationSequenceAndPositionAnalysis.R"))
```


```{r read_simplified_mismatch_data}
# Get file paths for the mismatch by read data
CPDMismatchData = list(rep1 = CPDTimepoints,
                       rep2 = CPDTimepoints)
for (i in seq_along(CPDMismatchData)) {
  for (j in seq_along(CPDMismatchData[[i]])) {
    CPDMismatchData[[i]][[j]] = fread(generateFilePath(
      deaminationSequenceAndPositionDataDirectory, dataTypeStrings$simplifiedMismatches, ".tsv",
      cellType = cellType, lesion = "CPD", timepoint = names(CPDMismatchData[[i]])[j],
      repitition = names(CPDMismatchData)[i]
    ))
  }
}

sixFourMismatchData = list(rep1 = sixFourTimepoints,
                           rep2 = sixFourTimepoints)
for (i in seq_along(sixFourMismatchData)) {
  for (j in seq_along(sixFourMismatchData[[i]])) {
    sixFourMismatchData[[i]][[j]] = fread(generateFilePath(
      deaminationSequenceAndPositionDataDirectory, dataTypeStrings$simplifiedMismatches, ".tsv",
      cellType = cellType, lesion = "6-4", timepoint = names(sixFourMismatchData[[i]])[j],
      repitition = names(sixFourMismatchData)[i]
    ))
  }
}
```


```{r CPD_mismatch_type_frequency}
for (i in 1:length(CPDMismatchData)) {
  for (j in 1:length(CPDMismatchData[[i]])) {
    plotMismatchTypeFrequencies(CPDMismatchData[[i]][[j]],
                                title = paste("CPD", names(CPDMismatchData)[i], 
                                              names(CPDMismatchData[[i]])[j], "Mismatch Type Frequency"))
  }
}
```


```{r 6-4_mismatch_type_frequency}
for (i in 1:length(sixFourMismatchData)) {
  for (j in 1:length(sixFourMismatchData[[i]])) {
    plotMismatchTypeFrequencies(sixFourMismatchData[[i]][[j]],
                                title = paste("6-4", names(sixFourMismatchData)[i], 
                                              names(sixFourMismatchData[[i]])[j], "Mismatch Type Frequency"))
  }
}
```


```{r CPD_mismatch_pos_frequency}
for (i in 1:length(CPDMismatchData)) {
  for (j in 1:length(CPDMismatchData[[i]])) {
    plotMismatchPositionFrequencies(CPDMismatchData[[i]][[j]], includedTypes = c("C>T"),
                                    title = paste("CPD", names(CPDMismatchData)[i], 
                                                  names(CPDMismatchData[[i]])[j], "C>T Mismatch Positions"))
    plotMismatchPositionFrequencies(CPDMismatchData[[i]][[j]], omittedTypes = c("C>T"),
                                    title = paste("CPD", names(CPDMismatchData)[i], 
                                                  names(CPDMismatchData[[i]])[j], "!C>T Mismatch Positions"))
  }
}
```


```{r 6-4_mismatch_pos_frequency}
for (i in 1:length(sixFourMismatchData)) {
  for (j in 1:length(sixFourMismatchData[[i]])) {
    plotMismatchPositionFrequencies(sixFourMismatchData[[i]][[j]], includedTypes = c("C>T"),
                                    title = paste("6-4", names(sixFourMismatchData)[i], 
                                                  names(sixFourMismatchData[[i]])[j], "C>T Mismatch Positions"))
    plotMismatchPositionFrequencies(sixFourMismatchData[[i]][[j]], omittedTypes = c("C>T"),
                                    title = paste("6-4", names(sixFourMismatchData)[i], 
                                                  names(sixFourMismatchData[[i]])[j], "!C>T Mismatch Positions"))
  }
}
```


```{r CPD_trinucleotide_context_analysis}
for (i in 1:length(CPDMismatchData)) {
  for (j in 1:length(CPDMismatchData[[i]])) {
    plotTrinucleotideContext(CPDMismatchData[[i]][[j]], includedTypes = c("C>T"),
                             title = paste("CPD", names(CPDMismatchData)[i], names(CPDMismatchData[[i]])[j],
                                           "C>T Mismatch Trinuc Context"))
  }
}
```


```{r 6-4_trinucleotide_context_analysis}
for (i in 1:length(sixFourMismatchData)) {
  for (j in 1:length(sixFourMismatchData[[i]])) {
    plotTrinucleotideContext(sixFourMismatchData[[i]][[j]], includedTypes = c("C>T"),
                             title = paste("6-4", names(sixFourMismatchData)[i], names(sixFourMismatchData[[i]])[j],
                                           "C>T Mismatch Trinuc Context"))
  }
}
```


```{r CPD_mismatch_position_frequencies_by_read_length, fig.width = 9, fig.height = 5}
plotPositionAcrossTimepointAndReadLength(CPDMismatchData$rep1, includedTypes = c("C>T"),
                                         title = "CPD C>T Mismatch Pos Freq Rep1")
plotPositionAcrossTimepointAndReadLength(CPDMismatchData$rep2, includedTypes = c("C>T"),
                                         title = "CPD C>T Mismatch Pos Freq Rep2")
plotPositionAcrossTimepointAndReadLength(CPDMismatchData$rep1, includedTypes = c("C>T"),
                                         title = "CPD C>T Mismatch Pos Freq Rep1", posType = FIVE_PRIME)
plotPositionAcrossTimepointAndReadLength(CPDMismatchData$rep2, includedTypes = c("C>T"),
                                         title = "CPD C>T Mismatch Pos Freq Rep2", posType = FIVE_PRIME)
```


```{r 6-4_mismatch_position_frequencies_by_read_length, fig.width = 9, fig.height = 5}
plotPositionAcrossTimepointAndReadLength(sixFourMismatchData$rep1, includedTypes = c("C>T"),
                                         title = "6-4 C>T Mismatch Pos Freq Rep1")
plotPositionAcrossTimepointAndReadLength(sixFourMismatchData$rep2, includedTypes = c("C>T"),
                                         title = "6-4 C>T Mismatch Pos Freq Rep2")
plotPositionAcrossTimepointAndReadLength(sixFourMismatchData$rep1, includedTypes = c("C>T"),
                                         title = "6-4 C>T Mismatch Pos Freq Rep1", posType = FIVE_PRIME)
plotPositionAcrossTimepointAndReadLength(sixFourMismatchData$rep2, includedTypes = c("C>T"),
                                         title = "6-4 C>T Mismatch Pos Freq Rep2", posType = FIVE_PRIME)
```


```{r read_mismatch_position_statistics}
CPDGroupedStats = list(rep1 = list(three_prime = NULL, five_prime = NULL),
                       rep2 = list(three_prime = NULL, five_prime = NULL))
for (i in seq_along(CPDGroupedStats)) {
  for (j in seq_along(CPDGroupedStats[[i]])) {
    CPDGroupedStats[[i]][[j]] = fread(generateFilePath(
      deaminationSequenceAndPositionDataDirectory, dataTypeStrings$mismatchPositionStats, ".tsv",
      cellType = cellType, lesion = "CPD", repitition = names(CPDGroupedStats)[i],
      strandPolarity = names(CPDGroupedStats[[i]])[j]
    ))
  }
}

sixFourGroupedStats = list(rep1 = list(three_prime = NULL, five_prime = NULL),
                           rep2 = list(three_prime = NULL, five_prime = NULL))
for (i in seq_along(sixFourGroupedStats)) {
  for (j in seq_along(sixFourGroupedStats[[i]])) {
    sixFourGroupedStats[[i]][[j]] = fread(generateFilePath(
      deaminationSequenceAndPositionDataDirectory, dataTypeStrings$mismatchPositionStats, ".tsv",
      cellType = cellType, lesion = "6-4", repitition = names(sixFourGroupedStats)[i],
      strandPolarity = names(sixFourGroupedStats[[i]])[j]
    ))
  }
}
```


```{r CPD_position_differences_across_read_lengths, fig.width = 9, fig.height = 5}
plotGroupedPositionStats(CPDGroupedStats$rep1$three_prime, CPDGroupedStats$rep1$five_prime, POS_DIFF,
                         title = "CPD C>T Mismatch Pos Diff Rep1",
                         xAxisBreaks = c(23:31))
plotGroupedPositionStats(CPDGroupedStats$rep2$three_prime, CPDGroupedStats$rep2$five_prime, POS_DIFF,
                         title = "CPD C>T Mismatch Pos Diff Rep2",
                         xAxisBreaks = c(23:31))
```


```{r 6-4_position_differences_across_read_lengths, fig.width = 9, fig.height = 5}
plotGroupedPositionStats(sixFourGroupedStats$rep1$three_prime, sixFourGroupedStats$rep1$five_prime, POS_DIFF,
                         title = "6-4 C>T Mismatch Pos Diff Rep1",
                         xAxisBreaks = c(23:31))
plotGroupedPositionStats(sixFourGroupedStats$rep2$three_prime, sixFourGroupedStats$rep2$five_prime, POS_DIFF,
                         title = "6-4 C>T Mismatch Pos Diff Rep2",
                         xAxisBreaks = c(23:31))
```


