---
title: "NHF1_TFBS_FigureGeneration"
author: "Ben Morledge-Hampton"
date: "2023-07-13"
output: html_document
params:
  bioinformaticsDirectory:
    label: "Bioinformatics Projects Directory"
    value: C:/Bioinformatics_Projects
    input: select
    choices: [C:/Bioinformatics_Projects, F:/Bioinformatics_Projects]
  filtering:
    label: "Filtering"
    value: NONE
    input: select
    choices: [NONE, TGG_filtered, TG_filtered]
---


```{r setup_chunk}
library(knitr)

cellType = "NHF1"
CPDTimepoints = list(`1h` = NULL, `8h` = NULL, `24h` = NULL, `48h` = NULL)
mismatchTypes = list(`C>T` = NULL, `CC>TT` = NULL)
TFBSs = list(`CTCF_known1_DHS` = NULL, `CTCF_known1_non-DHS` = NULL)

if (interactive()) {
  bioinformaticsDirectory = choose.dir(caption = "Select Bioinformatics_Projects Directory")
  filtering = readline("Filtering identifier (Input nothing for no filtering):")
  if (filtering == '') filtering = character()
} else {
  bioinformaticsDirectory = params$bioinformaticsDirectory
  filtering = params$filtering
  if (filtering == "NONE") filtering = character()
}
if (is.na(bioinformaticsDirectory)) stop("No bioinformatics directory given.")

deaminationDataDirectory = file.path(bioinformaticsDirectory, "deamination_determination", "data", cellType)
tfbsDataDirectory = file.path(deaminationDataDirectory,"TFBS_analysis")
```


```{r source_functions}
source(file.path(bioinformaticsDirectory, "deamination_determination", 'R',
                 "UsefulFileSystemFunctions.R"))
source(file.path(bioinformaticsDirectory, "deamination_determination", 'R',
                 "DeaminationTFBSAnalysis.R"))
```


```{r TFBS_relative_mismatch_position_plots}
xlim = NULL
for (CPDTimepoint in names(CPDTimepoints)) {
  for (mismatchType in names(mismatchTypes)) {
    for (TFBS in names(TFBSs)) {

      cpdTfbsRelativePositionData = fread(generateFilePath(
        tfbsDataDirectory, dataTypeStrings$tfbsRelativePositionCounts, ".tsv",
        cellType = cellType, lesion = "CPD", repitition = "all_reps", filtering = filtering,
        timepoint = CPDTimepoint, includedMismatches = mismatchType,
        additionalInformation = paste0(TFBS,"_related")
      ))

      plotTFBSRelativeCounts(cpdTfbsRelativePositionData, TFBS_RELATIVE_POSITION, sameStrand = TRUE, xlim = xlim,
                             title = paste(cellType, "CPD", CPDTimepoint, mismatchType, TFBS, "Same Strand"))
      plotTFBSRelativeCounts(cpdTfbsRelativePositionData, TFBS_RELATIVE_POSITION, sameStrand = FALSE, xlim = xlim,
                             title = paste(cellType, "CPD", CPDTimepoint, mismatchType, TFBS, "Opposite Strand"))
    }
  }
}
```


```{r TFBS_relative_three_prime_cut_site_plots}
xlim = NULL
for (CPDTimepoint in names(CPDTimepoints)) {
  for (mismatchType in names(mismatchTypes)) {
    for (TFBS in names(TFBSs)) {

      cpdTfbsRelativePositionData = fread(generateFilePath(
        tfbsDataDirectory, dataTypeStrings$tfbsRelativeCutSiteCounts, ".tsv", strandPolarity = THREE_PRIME,
        cellType = cellType, lesion = "CPD", repitition = "all_reps", filtering = filtering,
        timepoint = CPDTimepoint, includedMismatches = mismatchType,
        additionalInformation = paste0(TFBS,"_related")
      ))

      plotTFBSRelativeCounts(cpdTfbsRelativePositionData, TFBS_RELATIVE_THREE_PRIME_CUT_SITE, sameStrand = TRUE, xlim = xlim,
                             title = paste(cellType, "CPD", CPDTimepoint, mismatchType, TFBS, "Same Strand"))
      plotTFBSRelativeCounts(cpdTfbsRelativePositionData, TFBS_RELATIVE_THREE_PRIME_CUT_SITE, sameStrand = FALSE, xlim = xlim,
                             title = paste(cellType, "CPD", CPDTimepoint, mismatchType, TFBS, "Opposite Strand"))
    }
  }
}
```


```{r TFBS_relative_five_prime_cut_site_plots}
xlim = NULL
for (CPDTimepoint in names(CPDTimepoints)) {
  for (mismatchType in names(mismatchTypes)) {
    for (TFBS in names(TFBSs)) {

      cpdTfbsRelativePositionData = fread(generateFilePath(
        tfbsDataDirectory, dataTypeStrings$tfbsRelativeCutSiteCounts, ".tsv", strandPolarity = FIVE_PRIME,
        cellType = cellType, lesion = "CPD", repitition = "all_reps", filtering = filtering,
        timepoint = CPDTimepoint, includedMismatches = mismatchType,
        additionalInformation = paste0(TFBS,"_related")
      ))

      plotTFBSRelativeCounts(cpdTfbsRelativePositionData, TFBS_RELATIVE_FIVE_PRIME_CUT_SITE, sameStrand = TRUE, xlim = xlim,
                             title = paste(cellType, "CPD", CPDTimepoint, mismatchType, TFBS, "Same Strand"))
      plotTFBSRelativeCounts(cpdTfbsRelativePositionData, TFBS_RELATIVE_FIVE_PRIME_CUT_SITE, sameStrand = FALSE, xlim = xlim,
                             title = paste(cellType, "CPD", CPDTimepoint, mismatchType, TFBS, "Opposite Strand"))
    }
  }
}
```
