---
title: "NHF1_FeatureRelativeFigureGeneration"
author: "Ben Morledge-Hampton"
date: "2023-07-13"
output: html_document
params:
  bioinformaticsDirectory:
    label: "Bioinformatics Projects Directory"
    value: C:/Bioinformatics_Projects
    input: select
    choices: [C:/Bioinformatics_Projects, F:/Bioinformatics_Projects]
  filtering:
    label: "Filtering"
    value: NONE
    input: select
    choices: [NONE, TGG_filtered, TG_filtered]
---


```{r setup_chunk}
library(knitr)

cellType = "NHF1"
CPDTimepoints = list(`1h` = NULL, `8h` = NULL, `24h` = NULL, `48h` = NULL)
mismatchTypes = list(`C>T_CC>TT` = NULL)
TFBSs = list(`CTCF_known1_DHS` = NULL, `CTCF_known1_non-DHS` = NULL)
nucMaps = list(`hg19_mnase_all` = NULL)

if (interactive()) {
  bioinformaticsDirectory = choose.dir(caption = "Select Bioinformatics_Projects Directory")
  filtering = readline("Filtering identifier (Input nothing for no filtering):")
  if (filtering == '') filtering = character()
} else {
  bioinformaticsDirectory = params$bioinformaticsDirectory
  filtering = params$filtering
  if (filtering == "NONE") filtering = character()
}
if (is.na(bioinformaticsDirectory)) stop("No bioinformatics directory given.")

opts_chunk$set(dev = "png", dpi = 600, fig.width = 7, fig.height = 5, 
               fig.path = paste0(file.path("deamination_analysis_output",cellType,
                                           paste(c(filtering,"feature_relative_figures"), collapse = '_')),
                                 .Platform$file.sep))

deaminationDataDirectory = file.path(bioinformaticsDirectory, "deamination_determination", "data", cellType)
featureRelativeDataDirectory = file.path(deaminationDataDirectory,"feature_relative_analysis")
```


```{r source_functions}
source(file.path(bioinformaticsDirectory, "deamination_determination", 'R',
                 "UsefulFileSystemFunctions.R"))
source(file.path(bioinformaticsDirectory, "deamination_determination", 'R',
                 "DeaminationFeatureRelativeAnalysis.R"))
```


```{r TFBS_relative_mismatch_position_plots}
xlim = NULL
for (CPDTimepoint in names(CPDTimepoints)) {
  for (mismatchType in names(mismatchTypes)) {
    for (tfbs in names(TFBSs)) {

      featureRelativePositionData = fread(generateFilePath(
        featureRelativeDataDirectory, dataTypeStrings$featureRelativePositionCounts, ".tsv",
        cellType = cellType, lesion = "CPD", repitition = "all_reps", filtering = filtering,
        timepoint = CPDTimepoint, includedMismatches = mismatchType,
        additionalInformation = paste0(tfbs,"_related_strand_aligned")
      ))
      
      meanThreePrimeCutSiteDistanceData = fread(generateFilePath(
        featureRelativeDataDirectory, dataTypeStrings$featureRelativeMeanCutSiteDistance, ".tsv", strandPolarity = THREE_PRIME,
        cellType = cellType, lesion = "CPD", repitition = "all_reps", filtering = filtering,
        timepoint = CPDTimepoint, includedMismatches = mismatchType,
        additionalInformation = paste0(tfbs,"_related_strand_aligned")
      ))
      
      meanFivePrimeCutSiteDistanceData = fread(generateFilePath(
        featureRelativeDataDirectory, dataTypeStrings$featureRelativeMeanCutSiteDistance, ".tsv", strandPolarity = FIVE_PRIME,
        cellType = cellType, lesion = "CPD", repitition = "all_reps", filtering = filtering,
        timepoint = CPDTimepoint, includedMismatches = mismatchType,
        additionalInformation = paste0(tfbs,"_related_strand_aligned")
      ))

      plotFeatureRelativeCounts(featureRelativePositionData, FEATURE_RELATIVE_POSITION,
                                plotCountsMirror = TRUE, smoothCountsData = FALSE, mainYAxisLabel = "C>T Mismatches",
                                countsPlotColor = "black", countsMirrorColor = "gold2",
                                title = paste(cellType, "CPD", CPDTimepoint, mismatchType, tfbs, "Aligned Strands"))
      
      plotFeatureRelativeCounts(meanThreePrimeCutSiteDistanceData, FEATURE_RELATIVE_POSITION, MEAN_THREE_PRIME_CUT_SITE_DISTANCE,
                                smoothCountsData = FALSE, countsPlotColor = "red2", mainYAxisLabel = "Mean 3' Cut Site Distance",
                                meanCutSiteDistanceTable = meanFivePrimeCutSiteDistanceData,
                                cutSiteStrandPolarity = FIVE_PRIME, smoothMeanCutSiteDistance = FALSE,
                                title = paste(cellType, "CPD", CPDTimepoint, mismatchType, tfbs, "Aligned Strands"))
      
    }
  }
}
```


```{r nucleosome_relative_mismatch_position_plots}
xlim = NULL
for (CPDTimepoint in names(CPDTimepoints)) {
  for (mismatchType in names(mismatchTypes)) {
    for (nucMap in names(nucMaps)) {

      featureRelativePositionData = fread(generateFilePath(
        featureRelativeDataDirectory, dataTypeStrings$featureRelativePositionCounts, ".tsv",
        cellType = cellType, lesion = "CPD", repitition = "all_reps", filtering = filtering,
        timepoint = CPDTimepoint, includedMismatches = mismatchType,
        additionalInformation = paste0(nucMap,"_related_strand_aligned")
      ))
      
      meanThreePrimeCutSiteDistanceData = fread(generateFilePath(
        featureRelativeDataDirectory, dataTypeStrings$featureRelativeMeanCutSiteDistance, ".tsv", strandPolarity = THREE_PRIME,
        cellType = cellType, lesion = "CPD", repitition = "all_reps", filtering = filtering,
        timepoint = CPDTimepoint, includedMismatches = mismatchType,
        additionalInformation = paste0(nucMap,"_related_strand_aligned")
      ))
      
      meanFivePrimeCutSiteDistanceData = fread(generateFilePath(
        featureRelativeDataDirectory, dataTypeStrings$featureRelativeMeanCutSiteDistance, ".tsv", strandPolarity = FIVE_PRIME,
        cellType = cellType, lesion = "CPD", repitition = "all_reps", filtering = filtering,
        timepoint = CPDTimepoint, includedMismatches = mismatchType,
        additionalInformation = paste0(nucMap,"_related_strand_aligned")
      ))

      plotFeatureRelativeCounts(featureRelativePositionData, FEATURE_RELATIVE_POSITION,
                                plotCountsMirror = TRUE, smoothCountsData = FALSE, mainYAxisLabel = "C>T Mismatches",
                                title = paste(cellType, "CPD", CPDTimepoint, mismatchType, nucMap, "Aligned Strands"))
      
      plotFeatureRelativeCounts(meanThreePrimeCutSiteDistanceData, FEATURE_RELATIVE_POSITION, MEAN_THREE_PRIME_CUT_SITE_DISTANCE,
                                smoothCountsData = FALSE, countsPlotColor = "red2", mainYAxisLabel = "Mean 3' Cut Site Distance",
                                meanCutSiteDistanceTable = meanFivePrimeCutSiteDistanceData,
                                cutSiteStrandPolarity = FIVE_PRIME, smoothMeanCutSiteDistance = FALSE,
                                title = paste(cellType, "CPD", CPDTimepoint, mismatchType, nucMap, "Aligned Strands"))
      
    }
  }
}
```


```{r periodicity analysis}
library(mutperiodR)

for (CPDTimepoint in names(CPDTimepoints)) {
  for (mismatchType in names(mismatchTypes)) {
    for (nucMap in names(nucMaps)) {

        meanThreePrimeCutSiteDistanceData = fread(generateFilePath(
          featureRelativeDataDirectory, dataTypeStrings$featureRelativeMeanCutSiteDistance, ".tsv", strandPolarity = THREE_PRIME,
          cellType = cellType, lesion = "CPD", repitition = "all_reps", filtering = filtering,
          timepoint = CPDTimepoint, includedMismatches = mismatchType,
          additionalInformation = paste0(nucMap,"_related")
        ))
        
        meanFivePrimeCutSiteDistanceData = fread(generateFilePath(
          featureRelativeDataDirectory, dataTypeStrings$featureRelativeMeanCutSiteDistance, ".tsv", strandPolarity = FIVE_PRIME,
          cellType = cellType, lesion = "CPD", repitition = "all_reps", filtering = filtering,
          timepoint = CPDTimepoint, includedMismatches = mismatchType,
          additionalInformation = paste0(nucMap,"_related")
        ))
  
        print(paste(cellType, CPDTimepoint, mismatchType, nucMap, ":"))
        
        print("Mean 3` cut site distance:")
        periodAndSNR = getPeakPeriodicityAndSNR(
          meanThreePrimeCutSiteDistanceData[order(Feature_Relative_Mismatch_Pos)][abs(Feature_Relative_Mismatch_Pos) <= 60,
                                                                                  Mean_Three_Prime_Cut_Site_Distance], 5, 25)
        print(paste("  Peak Period:",periodAndSNR[1]))
        print(paste("  SNR:",periodAndSNR[2]))
        
        print("Mean 5` cut site distance:")
        periodAndSNR = getPeakPeriodicityAndSNR(
          meanFivePrimeCutSiteDistanceData[order(Feature_Relative_Mismatch_Pos)][abs(Feature_Relative_Mismatch_Pos) <= 60,
                                                                                  Mean_Five_Prime_Cut_Site_Distance], 5, 25)
        print(paste("  Peak Period:",periodAndSNR[1]))
        print(paste("  SNR:",periodAndSNR[2]))
        print("")
        
    }
  }
}

```

